tools/build_defs/cmake.bzl
Have explicit dict option "cache_entries" for passing CMake cache initializer key-values pairs to the rule.
This gives us ability to join user initializers and toolchain initializers. This might be useful with flags option.
=> cmake: add option cache_entries to pass cache initializers

WORKSPACE, examples/pybind11/BUILD, examples/pybind11/example/CMakeLists.txt, examples/pybind11/example/example.cpp
Demonstrates loading CMake scripts from externally built library for use in the dependent external library CMake build.
=> Add building example with pybind11

tools/build_defs/framework.bzl
Correct finding the root of the group of files:
it is either the path with the least number of fragments, if there are no other paths with the same number of fragments;
or the parent of the path with the least number of fragments.
(The case with workspace root for the external repository stays as is.)
Also, correct the code for adding to the PATH all immediate children - symbolic links and directories, of the created $EXT_BUILD_ROOT/bin directory. It was not working correctly (There are two variants for passing -type arguments for find command. Better we use the variant of code where we do not have to face that.)
=> correct finding the root of the filegroup/tree artifact, and path

WORKSPACE, examples/cmake_pcl/BUILD
more dependencies need to be provided
=> add pcl library targets - not ready yet

examples/BUILD, test/BUILD, test/cmake_text_tests.bzl, tools/build_defs/cc_toolchain_util.bzl, tools/build_defs/cmake.bzl, tools/build_defs/cmake_script.bzl, tools/build_defs/framework.bzl, tools/build_defs/os_info.bzl, workspace_definitions.bzl
+ tests for cmake script functions
=> Add a feature of generating CMake toolchain file and writing tools and flags information there

test/cmake_text_tests.bzl, tools/build_defs/cmake_script.bzl
+ tests for cmake script functions
=> correct CMake script test to use cmake path from workspace definition

examples/cmake_cares/BUILD, examples/cmake_nghttp2/BUILD, examples/ninja/BUILD, workspace_definitions.bzl
Also, provide a variable to put into dependencies, empty in case local ninja is installed, or containing the reference to ninja target
=> Correct dependency on Ninja: do not depend on ninja if it is local

examples/BUILD, examples/cmake_hello_world_lib/BUILD, examples/cmake_hello_world_lib/test_hello.sh
- with MSBuild generator (the path to it should be on the PATH)
- use CMake crosstool file
=> Modify hello world example with CMake to build on Windows

examples/configure_gnuplot/BUILD, for_workspace/utils_osx.sh, for_workspace/utils_unix.sh, for_workspace/utils_win.sh
+ assert libz, freetype, libpng to be found by configure for libgd
=> Adjust configure-make: also replace absolute paths in -config files

tools/build_defs/cc_toolchain_util.bzl
... with cc_common.create_library_to_link
=> Replace cc_common.create_symlink_library_to_link calls

tools/build_defs/framework.bzl
We should not extract all linkopts from the transitive depset just to manually merge them; they are already being merged when the merging of the linking info happens.
Use just linking info merging + pass direct value of current target's linkopts.
Please also note #120 planned to be done.
=> Remove incorrect merging of the linkopts

tools/build_defs/cmake.bzl, tools/build_defs/configure.bzl, tools/build_defs/framework.bzl, tools/build_defs/version.bzl
- create provider for the parameters, passed to the callback
- correct documentation
=> Improve documentation and naming for the configuration callback

for_workspace/utils_osx.sh, for_workspace/utils_unix.sh, for_workspace/utils_win.sh
.. for directory contents copying
=> Simplify shell utils: remove unused methods, use --no-target-directory

tools/build_defs/framework.bzl
this way is a tad more readable imho, but feel free to reject if you disagree!
=> minor code cleanup

tools/build_defs/framework.bzl
=> framework: extract environment variable declaration into separate part

examples/BUILD, examples/cmake_hello_world_lib/binary/BUILD, examples/cmake_hello_world_lib/binary/CMakeLists.txt, examples/cmake_hello_world_lib/binary/src/CMakeLists.txt, examples/cmake_hello_world_lib/binary/src/hello.c, examples/cmake_hello_world_lib/binary/src/hello.h, examples/cmake_hello_world_lib/binary/src/main.c, tools/build_defs/framework.bzl
Add CMake test for building a binary and using that binary in a test.
(simple change)
=> Put each of binary files into OutputGroupInfo under its name.

for_workspace/utils_osx.sh, for_workspace/utils_unix.sh, for_workspace/utils_win.sh
=> adds *.cmake as regex to be searched by replace_in_files

tools/build_defs/new_11_2018/framework.bzl, tools/build_defs/old_10_2018/framework.bzl
=> In the generated repository, refer to the "parent" as @rules_foreign_cc

tools/build_defs/new_11_2018/framework.bzl, tools/build_defs/old_10_2018/framework.bzl
=> When cmake_external script fails, do not delete build directory.

tools/build_defs/new_11_2018/framework.bzl
=> Fix create_compilation_context call to match changed Starlark API

.bazelci/config.yaml, .bazelignore, WORKSPACE, examples/.bazelignore, examples/.bazelrc, examples/BUILD, examples/WORKSPACE, examples/boost/BUILD, examples/build_cmake_itself/BUILD, examples/cc_configure_make/BUILD, examples/cmake/BUILD, examples/cmake/test_libpng.sh, examples/cmake_android/BUILD, examples/cmake_cares/BUILD, examples/cmake_hello_world_lib/binary/BUILD, examples/cmake_hello_world_lib/shared/BUILD, examples/cmake_hello_world_lib/static/BUILD, examples/cmake_nghttp2/BUILD, examples/cmake_pcl/BUILD, examples/cmake_synthetic/BUILD, examples/configure_gnuplot/BUILD, examples/examples_repositories.bzl, examples/pybind11/BUILD, for_workspace/cmake_build.bzl, tools/build_defs/new_11_2018/framework.bzl
This will help to define native tools toolchains for examples
=> Reorganize examples to be in a separate workspace

examples/configure_gnuplot/BUILD
provide more hints for configure-make example
=> Fix reference to environment variables in examples,

.bazelci/config.yaml, examples/BUILD, examples/cmake_hello_world_lib/static/BUILD, tools/build_defs/cmake_script.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
All custom tools (MS Visual Studio) information goes into
windows_commands.bzl
=> Launch at least some Windows tests on CI

examples/bison/BUILD, examples/examples_repositories.bzl
=> Add bison/yacc example (configure & make)

.bazelignore, toolchains_examples/.bazelrc, toolchains_examples/BUILD, toolchains_examples/README.md, toolchains_examples/WORKSPACE, toolchains_examples/additional_toolchains.bzl, toolchains_examples/fancy_platform_commands.bzl, toolchains_examples/test_platform_name_rule.bzl, tools/build_defs/shell_toolchain/polymorphism/generate_overloads.bzl, tools/build_defs/shell_toolchain/toolchains/BUILD, tools/build_defs/shell_toolchain/toolchains/defs.bzl, tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl, tools/build_defs/shell_toolchain/toolchains/ws_defs.bzl, workspace_definitions.bzl
(please see the commit comments)
=> Register shell toolchain implementations in the correct order and allow customization

tools/build_defs/shell_toolchain/polymorphism/generate_overloads.bzl
make code compatible with --incompatible_bzl_disallow_load_after_statement
=> Fix generated code to have load statements strictly in the beginning

for_workspace/repositories.bzl
=> Remove rules_apple dependency

examples/.bazelignore, examples/use_malloc/BUILD, examples/use_malloc/WORKSPACE, examples/use_malloc/hello.cpp
Adding the example for demonstration purposes; related issue: #227
=> Example with malloc attribute, currently not working

tools/build_defs/cc_toolchain_util.bzl
This PR migrates rules_foreign_cc for bazelbuild/bazel#7793
=> Migrate for incompatible_require_ctx_in_configure_features

test/standard_cxx_flags_test/tests.bzl, tools/build_defs/boost_build.bzl, tools/build_defs/cmake.bzl, tools/build_defs/configure.bzl
https://github.com/bazelbuild/bazel/issues/7260
=> Migrate for --incompatible_enable_cc_toolchain_resolution

examples/cmake_hello_world_lib/static/BUILD, examples/cmake_hello_world_lib/static/test_hello.sh, test/standard_cxx_flags_test/tests.bzl
See https://github.com/bazelbuild/bazel/issues/6622
=> Windows: tests now work with native test wrapper

tools/build_defs/framework.bzl
=> Migrate for --incompatible_depset_is_not_iterable

tools/build_defs/framework.bzl, workspace_definitions.bzl
- convert depset to list for iteration (libraries to link)
- _build_tools() are just creating the file, not contributing anything to the text of constructed BUILD file, so make a call to this method separately.
=> Fix the code to work with Bazel HEAD:

tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
=> Add -H to find in symlink_contents_to_dir

tools/build_defs/configure_script.bzl
=> Fix make() rule to run make commands sequentially and not in parallel.

examples/examples_repositories.bzl
Context: https://github.com/bazelbuild/bazel/issues/10270
=> Mirror all http_archives.

for_workspace/repositories.bzl
Update CMake to 3.17.2. Also add a `sha256` sum to the `http_archive` hich was missing.
=> Update CMake version

for_workspace/repositories.bzl
Update these three archives to the latest stable release.
I'm not looking for any particular feature or security fix. I was doing some other cleanup and figured I might as well update these.
=> Update CMake, Ninja & bazel_skylib

test/BUILD, tools/build_defs/cmake.bzl, tools/build_defs/configure_script.bzl, tools/build_defs/make.bzl
Apply Buildifier formatting to existing code.
=> Buildifier formatting

for_workspace/repositories.bzl, tools/build_defs/native_tools/BUILD
In addition, this adds the `manual` tag to some very expensive targets.
=> Wrap dependencies in a `maybe` macro

README.md
=> Updated CI build tag to only user the main branch

docs/README.md
Simple regeneration of the documentation to pick up new changes.
=> Updated docs

for_workspace/install_ws_dependency.bzl
If this macro is actually used, please open a new issue or reply to this PR explaining your use for it.
=> Added deprecation notice to `install_ws_dependency`

for_workspace/cmake_build.bzl, for_workspace/make_build.bzl, test/expected/inner_fun_text.txt, toolchains_examples/fancy_platform_commands.bzl, tools/build_defs/framework.bzl, tools/build_defs/shell_toolchain/toolchains/commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
Reviving this change from c835382026896f4316b3a1af9164977eeb46abea.
Fixes #478.
=> Build under Bazel sandbox instead of /tmp

docs/README.md, toolchains/prebuilt_toolchains.py
=> Updated documentation

toolchains/prebuilt_toolchains.bzl, toolchains/prebuilt_toolchains.py, toolchains/prebuilt_toolchains_repository.bzl
=> Fixes to cmake toolchain so it can find CMAKE_ROOT correctly

ARCHITECTURE.md, examples/README.md, examples/third_party/README.md, toolchains/README.md
I have some changes prepped for this already but would like to get some input first. All comments are welcome.
cc @jsharpe
=> Added architecture documentation

README.md
This fixes some docs missed by #556
=> Updated top level docs

foreign_cc/boost_build.bzl, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/ninja.bzl, foreign_cc/private/cmake_script.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/make_script.bzl, test/cmake_text_tests.bzl
Keep the commands as a list of strings until the point the script is created.
=> Keep lines of scripts as a list of commands

README.md
Bringing in the fix from https://github.com/bazelbuild/rules_foreign_cc/pull/578
Thanks!
=> Fixed min version in docs

foreign_cc/built_tools/ninja_build.bzl, toolchains/BUILD.bazel
This should be a nice optimization to what was there before but function the same
=> Built ninja tools no longer carry the entire source tree

foreign_cc/private/make_script.bzl
This change is necessary if a hermetic cc toolchain is being used
(e.g. gcc checked into the workspace repository)
Testing: Successfully built zlib using configure_make and a custom
hermetic cc toolchain.
=> absolutize tool paths for (configure_)make (#593)

foreign_cc/private/shell_toolchain/toolchains/access.bzl, foreign_cc/private/shell_toolchain/toolchains/function_and_call.bzl, foreign_cc/private/shell_toolchain/toolchains/impl/default_commands.bzl, foreign_cc/private/shell_toolchain/toolchains/impl/linux_commands.bzl, foreign_cc/private/shell_toolchain/toolchains/impl/macos_commands.bzl, foreign_cc/private/shell_toolchain/toolchains/impl/windows_commands.bzl, test/convert_shell_script_test.bzl
This addresses a buildifier defect, [name-conventions](https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#name-conventions).
=> Fixed provider name which was violating naming conventions

foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/private/cmake_script.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/framework/helpers.bzl, foreign_cc/private/framework/toolchains/commands.bzl, foreign_cc/private/framework/toolchains/linux_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl, foreign_cc/private/make_script.bzl, foreign_cc/private/run_shell_file_utils.bzl, test/cmake_text_tests.bzl
- enable_tracing
- disable_tracing
- script_extension
- shebang
=> Added new foreign_cc framework commands

foreign_cc/private/cc_toolchain_util.bzl
This should have no functional change. Just minor cleanup.
=> Cleanup cc_toolchain utils

examples/third_party/BUILD.bazel, examples/third_party/subversion/BUILD.subversion.bazel
This PR enables tests from #650
The credit for this PR goes to @jheaff1 for catching this (and for writing the tests in the first place). Huge thanks!! 🙏 😄
=> Enabled tests from #650

.github/workflows/pages.yaml, docs/BUILD.bazel, docs/index.md
This also enables builds to test docs generation in pull requests.
=> Updated docs to be more appropriate when viewing `main`

foreign_cc/private/framework.bzl
=> Always set use_default_shell_env=True so that action_env is propagated.

examples/WORKSPACE.bazel, foreign_cc/built_tools/cmake_build.bzl, foreign_cc/private/framework.bzl
=> Use configure_make to build cmake.

.bazelci/config.yaml, examples/make_simple/code/Makefile, examples/make_simple/code/clang_wrapper.sh, examples/third_party/BUILD.bazel, foreign_cc/built_tools/make_build.bzl, foreign_cc/built_tools/ninja_build.bzl, foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/private/framework.bzl
This pull request fixes the issue of GNU Make failing to build on Windows
=> Build make windows

foreign_cc/private/framework.bzl
If a user specifies a PATH value as part of an `env` attribute, the
value will be prepended to the existing PATH.
An example requirement for this change is that the MSVC build of
OpenSSL requires that the Netwide Assembler (NASM) must be on the
PATH.
=> Prepend user-specified PATH to existing PATH

version.bzl
This release should include the following PRs still in work:
- https://github.com/bazelbuild/rules_foreign_cc/pull/703
Please comment additional PRs that should be considered.
=> Release 0.5.0

.github/workflows/pages.yaml, docs/root/src/index.md
This should be merged following https://github.com/bazelbuild/rules_foreign_cc/pull/740 and a new `0.5.0` release
=> Updated 0.5.0 docs

foreign_cc/make.bzl
This only addresses the reported issue but does not address the gap in coverage but it's important to have a fix out
closes https://github.com/bazelbuild/rules_foreign_cc/issues/745
=> Fix missing parameter

version.bzl
This release contains fixes to the `0.5.0` release
- https://github.com/bazelbuild/rules_foreign_cc/pull/746
=> Release 0.5.1

examples/make_simple/BUILD.bazel, foreign_cc/make.bzl
=> Re-add setting of PREFIX variable in make invocation

examples/third_party/BUILD.bazel, examples/third_party/apr/BUILD.apr.bazel, examples/third_party/apr/apr_repositories.bzl, examples/third_party/apr/windows_winnt.patch, foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/private/framework.bzl
This PR modifies `rules_foreign_cc` to be able to build apr for MSVC on Windows
=> Build apr for MSVC on Windows

foreign_cc/built_tools/make_build.bzl
Might help with the issue seen in #810.
=> Explicitly turn off guile support in built version of GNU make

.github/docs-0.1.0.patch, .github/docs-0.2.0.patch, .github/docs-0.3.0.patch
This fixes a regression from https://github.com/bazelbuild/rules_foreign_cc/pull/794
=> Fixed docs

foreign_cc/extensions.bzl, foreign_cc/private/framework/toolchain.bzl, foreign_cc/repositories.bzl, toolchains/built_toolchains.bzl, toolchains/prebuilt_toolchains.bzl, toolchains/prebuilt_toolchains.py
Initial changes required to support bzlmod.
=> Initial bzlmod support

version.bzl
closes https://github.com/bazelbuild/rules_foreign_cc/issues/882
=> Release `v0.8.0`

examples/WORKSPACE.bazel
I created a release just to get past this issue with bazel HEAD
=> Update to new rules_apple release

foreign_cc/private/framework/toolchains/linux_commands.bzl, test/convert_shell_script_test.bzl, test/expected/inner_fun_text.txt
-t option to ln is not defined under POSIX and (at least) busybox does
not implement it. Rewrite the code to use only POSIX options to ln.
=> Make tests pass on busybox

WORKSPACE.bazel, examples/WORKSPACE.bazel, test/detect_root_test/WORKSPACE.bazel, test/standard_cxx_flags_test/WORKSPACE.bazel
migrating to rbe_preconfig 
https://github.com/bazelbuild/continuous-integration/issues/1404
Fixes: https://github.com/bazelbuild/rules_foreign_cc/issues/951
=> migrating to rbe_preconfig

foreign_cc/repositories.bzl, toolchains/built_toolchains.bzl
=> Add make 4.4

foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/make.bzl, foreign_cc/private/transitions.bzl
The macro will be used in an upcoming commit that adds meson support
=> Rename make_variant to foreign_cc_rule_variant

foreign_cc/private/cc_toolchain_util.bzl
=> Pass must_keep_debug = False to cc_common.create_link_variables

foreign_cc/boost_build.bzl, foreign_cc/cmake.bzl, foreign_cc/make.bzl, foreign_cc/meson.bzl, foreign_cc/ninja.bzl
=> Advertise CcInfo provider

examples/MODULE.bazel, examples/WORKSPACE.bazel
Fixes #1172
CC Greenteam @meteorcloudy @Mai93
=> Fixes the CI failure at Bazel@HEAD

foreign_cc/private/framework/toolchains/freebsd_commands.bzl, foreign_cc/private/framework/toolchains/linux_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl
=> Use a sed delimiter that is unlikely to appear in the input

foreign_cc/extensions.bzl
Revert change that was committed accidentally directly to main
=> Revert inadvertent direct commit to main

examples/third_party/libpng/libpng_repositories.bzl
=> chore(deps): Update libpng

toolchains/cmake_versions.bzl, toolchains/prebuilt_toolchains.bzl, toolchains/prebuilt_toolchains.py
I also added a small bit of debug logging to the python script.
=> chore: update cmake versions

examples/third_party/zlib/zlib.patch, examples/third_party/zlib/zlib_repositories.bzl
=> Update zlib version

foreign_cc/built_tools/make_build.bzl
=> fix: fix make_build.bzl for macos.

.github/workflows/release_prep.sh
=> docs: Update instructions for WORKSPACE
