framework_example/cmake/BUILD, tools/build_defs/cc_linking_util.bzl, tools/build_defs/framework.bzl
i.e. not single libraries, because in general case several build targets
can be created by a single CMake/configure-make build, and several of them linked to the next dependency
=> provide several libraries as outputs from external build rules

framework_example/cmake/BUILD, tools/build_defs/cmake.bzl, tools/build_defs/framework.bzl, tools/build_defs/utils.sh
this way the users can influence which install prefix will appear in the
generated code
install prefix have to be relative - we are doing the hermetic build
modify our shell script to copy the result of the build into the target directory
(we can not leave it in temp directory, it will be deleted)
=> make cmake rule accept install-prefix option

examples/cmake_android/BUILD
because now it gets passed with the cc_toolchain files
=> do not pass android ndk as additional dependency

tools/build_defs/cmake.bzl
Unfortunately, the prefix is never relative.
If the relative value is passed, current directory is used as base,
and the real prefix is $(pwd)/<relative-prefix>
However, keep any value, passed by user, as finally outside the build that value can be used.
=> install prefix: indicate relative value with "./"

tools/build_defs/cmake.bzl, tools/build_defs/framework.bzl
Some libraries define not only C/C++ libraries and headers, but also
scripts for finding this libraries (pkg_config, CMake find/config scripts).
Another important use case is defining CMake functions to be used in the CMake build of the dependent targets.
As for CMake such scripts are searched for in the number of directory path combinations, relative to CMAKE_INSTALL_PREFIX, including for both Unix and Windows,
`<prefix>/<name>*/(lib/<arch>|lib|share)/cmake/<name>*/          (W/U)
<prefix>/<name>*/(lib/<arch>|lib|share)/<name>*/                (W/U)
<prefix>/<name>*/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (W/U)`
acceptable solution would be copying the whole CMake install directory under the dependencies root $EXT_BUILD_DEPS, which is passed as CMAKE_INSTALL_PREFIX.
For the …
=> Important refactoring of the $EXT_BUILD_DEPS directory structure.

tools/build_defs/cc_toolchain_util.bzl, tools/build_defs/cmake.bzl, tools/build_defs/framework.bzl, workspace_definitions.bzl
apparently, is it possible to just take the needed environment variables from cc_common, and not do any calls to rules_apple or platform-dependent initialization
=> correct work in osx: take environment from cc_common

test/cmake_text_tests.bzl, tools/build_defs/cmake_script.bzl
This allows using locally installed libraries to be found by CMake
+ test
=> Merge CMAKE_PREFIX_PATH, passed by user, with $EXT_BUILD_DEPS

tools/build_defs/framework.bzl
We should take the default PATH passed by Bazel, not that from cc_toolchain for Windows, because the PATH under msys2 is different and that is which we need for shell commands
=> Correct "use default shell environment" action argument

examples/cmake_synthetic/BUILD, examples/cmake_synthetic/liba/src/CMakeLists.txt, examples/cmake_synthetic/libb/src/CMakeLists.txt
- On Linux, lib is added to the name
- Use CMake crosstool file (needed for Windows)
=> Adapt tests for Windows: set .a library name, use crosstool file

for_workspace/compilation_mode.bzl, test/cmake_text_tests.bzl, tools/build_defs/cc_toolchain_util.bzl, tools/build_defs/cmake.bzl, tools/build_defs/cmake_script.bzl, tools/build_defs/framework.bzl, workspace_definitions.bzl
CMAKE_BUILD_TYPE=DEBUG (otherwise RELEASE)
Can be overriden by user passing CMAKE_BUILD_TYPE in cache_entries
=> Pass the value of --compilation_mode dbg to the rule and to CMake

.bazelci/config.yaml, examples/BUILD
=> Exclude synthetic tests from Ubuntu 16 on CI

tools/build_defs/boost_build.bzl, tools/build_defs/cmake.bzl, tools/build_defs/framework.bzl
reason: configure-make should reuse the linking and compilation structures created by framework function
=> Refactor framework function: configure_script to be a callback

examples/cmake/BUILD, tools/build_defs/configure.bzl, tools/build_defs/configure_script.bzl, tools/build_defs/framework.bzl, tools/build_defs/version.bzl
- to have the same interface as cc_library to hide the "implementation details",
so that the information about the install directory and its contents of non-direct external dependencies of external library was available for external build
- this is particularly needed for configure-make rule, where we do not control the way needed libraries are found, so we want to provide the install directory and the -L, -I flags (include and library directories to be searched) consistently,
pointing to the directories under $EXT_BUILD_DEPS
- as a side effect, *.la files that contained links to absolute paths of dependencies (pointing somewhere under ...sandbox/bazel-out/...) now will point to directories under $EXT_BUILD_DEPS and so will be replaced correctly/will not point to paths under the previous …
=> External C/C++ libraries rules need to pass transitive info

README.md, examples/boost/BUILD, examples/cmake_pcl/BUILD, tools/build_defs/boost_build.bzl
Then --with-<library> parameter can be passed to build only that library
Modify examples to demonstrate how to use it.
However, building examples takes too long time, so do not include them into the tests.
=> Improve the boost rule including user_options attribute.

.bazelignore
Since it is a separate workspace
=> Put examples/crosstool into .bazelignore

examples/BUILD, examples/print_bazel_version.sh, examples/select_windows_tests.bzl, workspace_definitions.bzl
As Bazel 0.22.0 is broken for rules_foreign_cc on Windows, we do not want to run any tests with this version on CI. So we are selecting the list of tests to run according to recorded-in-workspace Bazel version.
But list of tests can not be empty! Instead, have a test that just prints the Bazel version.
=> Correction for what tests to run on CI on Windows with Bazel 0.22.0

README.md
- with Bazel 0.22.0, no flags are required to use rules_foreign_cc
- improve Bazel versions related information
- add link to "rules_foreign_cc take-aways"
=> Update README.md because of Bazel 0.22.0 release

.gitignore
Originally from #204. Ignores JetBrains IDE files (e.g. IntelliJ), the IntelliJ bazel plugin, and bazel.
=> Adds a gitignore.

tools/build_defs/configure.bzl, tools/build_defs/configure_script.bzl
Some configure scripts rely on being called from their parent directory (they call other files as if they are in the same directory). For this case, we should copy/symlink the contents of the directory under our build root, and run configure from there.
New attribute in configure_make rule: "configure_in_place".
Also, add documentation for configure_make.
=> For configure_make, allow to run configure in place

test/cmake_text_tests.bzl, tools/build_defs/cmake_script.bzl
If the user passes empty string for some cache entry, for instance,
CMAKE_BUILD_TYPE, then the corresponding computed value
(computed from the Bazel's build type or Bazel C/C++ toolchain)
should not be used.
I.e., user passes "CMAKE_BUILD_TYPE": "", and there will be no
-DCMAKE_BUILD_TYPE in the cmake call.
=> cmake_external: allow user to suppress computed cache entries

toolchains_examples/fancy_platform_commands.bzl, tools/build_defs/new_11_2018/framework.bzl, tools/build_defs/old_11_2018/framework.bzl, tools/build_defs/old_12_2018/framework.bzl, tools/build_defs/shell_script_helper.bzl, tools/build_defs/shell_toolchain/toolchains/commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl, tools/build_defs/version.bzl
- extract wrapper script creation into a separate function,
- simplify the script and log names, also output the wrapper script text,
- introduce more shell primitives
related to #204
=> Improve outputs handling: wrapper script in shell-abstract manner

tools/build_defs/old_11_2018/cc_toolchain_util.bzl, tools/build_defs/old_12_2018/cc_toolchain_util.bzl
=> Correct check for shared library requiring also interface library on win

WORKSPACE, examples/WORKSPACE
Breakage: https://buildkite.com/bazel/rules-foreign-cc/builds/273#2f3c5420-5cfe-4415-9e4e-47607aa6279a
Also see https://github.com/bazelbuild/rules_jvm_external/pull/33#issuecomment-471969979
cc @meteorcloudy @irengrig
=> Fix Buildkite breakage caused by gmaven_rules rename

WORKSPACE, examples/WORKSPACE, examples/cmake_crosstool/WORKSPACE, examples/with_prebuilt_ninja_artefact/WORKSPACE, for_workspace/repositories.bzl, test/cmake_text_tests.bzl, test/convert_shell_script_test.bzl, workspace_definitions.bzl
In this PR:
- Update `@bazel_skylib` to 0.8.0, which has a
Windows-compatible unittest.bzl
- Fix unittest-using tests. Correct usage of
`unittest.end(env)` is to return its value.
Result: //test:all now passes with Bazel 0.25.0rc3
and --incompatible_windows_native_test_wrapper
=> Windows, tests: fix for native test wrapper

tools/build_defs/boost_build.bzl
Fixes a bug where bootstrap options weren't being passed.
=> Boost bootstrap_options not working

examples/apache_httpd/BUILD, examples/apache_httpd/t.sh, examples/examples_repositories.bzl
An example of building Apache Httpd and run it in a script.
Demonstrates usage of LD_LIBRARY_PATH for binding shared libraries.
As I was not able to make the created httpd executable to absorb what I was passing to the configuration script with "-Wl,-rpath -Wl,<libdir>" 
- I tried passing $ORIGIN to <libdir>, or something else, but the problem is the Apache configuration script also invokes libtool and passes the current directory as RPATH, and I can not think of a nice way of avoiding this.
So passing the runtime paths to the built shared libraries in LD_LIBRARY_PATH seems a good option.
I may write a wrapper rule/function for running executables this way; this may be already a case with Bazel C/C++ platform, I will clarify this.
Related issue: #241
=> Add working example for #241

tools/build_defs/cmake_script.bzl
This allows users to set this to an empty string if they want to disable
it. Related https://github.com/bazelbuild/rules_foreign_cc/issues/252
=> Allow ranlib to be overridden

for_workspace/bazel_version.bzl, tools/build_defs/cc_toolchain_util.bzl, workspace_definitions.bzl
This PR adds @bazel_version repository which contains single def.bzl
file which contains a BAZEL_VERSION constant that can be used to perform
conditional logic bazed on the Bazel version.
As a result, rules_foreing_cc are now compatible with Bazel 0.24 - 0.27
(at least regarding configure_features :)
=> Guard cc_common.configure_features with a version check

tools/build_defs/cc_toolchain_util.bzl
This PR fixes the bug introduced in https://github.com/bazelbuild/rules_foreign_cc/pull/270.
hlopko@ should not be allowed to code undercaffeinated.
=> Use forward compatible version of _configure_features

examples/nghttp2.patch
The line number doesn't match the exact location of the position of the content. This is tolerable with patch command line tool, but it won't work with a more strict patch implementation.
Context: https://github.com/bazelbuild/bazel/pulls
=> Fix patch file for nghttp2

test/cmake_text_tests.bzl, tools/build_defs/cmake_script.bzl
These values are case-sensitive in cmake and give this error currently:
```
CMake Error at CMakeLists.txt:23 (message):
CMAKE_BUILD_TYPE must be one of: Debug, Release (current value: 'RELEASE')
```
=> fix(cmake): Use "Debug" and "Release" instead of "DEBUG" and "RELEASE"

examples/BUILD, examples/cmake_hello_world_variant/BUILD, examples/cmake_hello_world_variant/test_hello_world.sh, examples/examples_repositories.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
Filter files by types, where the absolute paths need to be replaced.
Fixes #279
=> Fix replace_in_files function in windows_commands.bzl

examples/WORKSPACE, examples/cmake_android/BUILD
The previous gmaven_rules usage was broken, this is the new supported
way to download these dependencies.
=> Switch to rules_jvm_external

.bazelci/config.yaml
Currently there aren't any actual test targets for the NDK example, but
building it is still useful to verify.
=> Build Android example on CI

.bazelci/config.yaml, examples/cc_configure_make/BUILD, tools/build_defs/cc_toolchain_util.bzl, tools/build_defs/cmake.bzl, tools/build_defs/cmake_script.bzl
- for CMake, pass "<TARGET>" as the output file when forming linker flags with cc_common. CMake will later replace <TARGET> with the actual output file. Fill CMAKE_C_CREATE_ARCHIVE and CMAKE_CXX_CREATE_ARCHIVE CMake variables with 'CMAKE_AR %Bazel-link-flags% <OBJECTS>' call, where CMAKE_AR will take the path to libtool.
Related documentation: https://cmake.org/cmake/help/v3.15/variable/CMAKE_LANG_ARCHIVE_CREATE.html?highlight=cmake_%20lang%20_archive_create
- for configure_make, for the libevent example, we need to skip specifying the libtool from Bazel's toolchain as a linker, because libevent script uses it's own libtool and manages to pass the output file to it, but not to the libtool we are passing. Let it do so as it is a customized script.
Do it with specifying empty string for the …
=> Adapt rules_foreign_cc for working with libtool instead of ar.

.bazelci/config.yaml, examples/BUILD, examples/cmake_synthetic/BUILD, examples/cmake_synthetic/libb/BUILD, examples/cmake_synthetic/libc/BUILD, examples/cmake_synthetic/libc/CMakeLists.txt, examples/cmake_synthetic/libc/src/CMakeLists.txt, examples/cmake_synthetic/libc/src/libc.cpp, examples/cmake_synthetic/libc/src/libc.h, tools/build_defs/framework.bzl
- it is possible that some duplicate libraries, built with Bazel, will be passed as inputs to cmake_external or configure_make. rules_foreign_cc should filter duplicates out rather then fail.
- add a test (which just builds the target) //cmake_synthetic:lib_with_duplicate_transitive_bazel_deps
=> Be resilient with Bazel-built transitive dependencies duplicates

tools/build_defs/framework.bzl
When executed without sandbox, target- and host- configured targets are created in the same execution root with the same names.
Apparently, it is not the problem for build outputs, but deps directory that is created by script.
What is even more problematic is that this directory can be accessed while building this target in parallel for different configurations. So even if we clean it before using, we might break the build of the parallel target.
Solution: create temp directory to be used as deps directory.
(Additionally, this demonstrates the benefits of sandboxed execution.)
How to execute without sandbox:
bazel build/test --spawn_strategy=standalone
How to reproduce the problem: 
For instance, have the results of cmake_external/configure_make be consumed by genrule in tools attribute. …
=> Solution for building without sandbox and EXT_BUILD_DEPS containing files from building this same target for other (host, other target) configuration

tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
Use `cygpath` in case it is available, `pwd` otherwhise. `pwd -W` does not work within Cygwin.
=> Improve cygwin compatibility

tools/build_defs/framework.bzl, tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
- we can not modify files under Bazel's output directory
- so we can not modify pkg_config files, written there, for instance
- solution: only replace absolute paths in the files being created by the current target,
using the environment variable as the replacement value ($EXT_BUILD_DEPS)
=> Fix permission problem with replacing absolute path with sed, #306

tools/build_defs/cc_toolchain_util.bzl, workspace_definitions.bzl
=> Prefixes bazel_version so that it doesn't conflict with other libraries.

tools/build_defs/framework.bzl
For consuming Bazel-built targets as dependencies, do not use quote_includes from CcInfo, as they are not used for anything related to the particular library, but contain references to the gendir and bin directories, which seems hardly useful. (We expect Bazel targets to describe their include directories and headers explicitly).
Rules_foreign_cc also currently is not using CcInfo.quote_includes.
Having them leads to symlinking directory trees without any reason.
Tests: we already have tests for transitive Bazel dependencies (//cmake_synthetic:test_bazel_transitive_deps, //cmake_with_bazel_transitive:test, //configure_with_bazel_transitive:test)
=> For Bazel-built dependencies, do not symlink generic directories under includes

README.md, examples/BUILD, examples/cmake_working_dir/BUILD, examples/cmake_working_dir/source_root/cmake_dir/CMakeLists.txt, examples/cmake_working_dir/source_root/src/liba.cpp, examples/cmake_working_dir/source_root/src/liba.h, examples/cmake_working_dir/test_liba.cpp, tools/build_defs/cmake.bzl, tools/build_defs/framework.bzl
For LLVM case, when main CMakeLists.txt is in the /llvm subdirectory in the source tree
=> Allow to specify working directory for cmake_external

examples/BUILD, examples/configure_libunwind/BUILD, examples/configure_libunwind/libunwind_test.c, examples/configure_mpc/BUILD, examples/configure_mpc/mpc_test.c, examples/examples_repositories.bzl, tools/build_defs/configure.bzl, tools/build_defs/configure_script.bzl
Some libraries distributed as tarballs use older versions of autotools to generate some of the scripts such as libtool. Some of these versions apparently do not handle certain things well, such as putting EXT_BUILD_DEPS in .la and .pc files. I was able to get them working by adding support to run autoreconf before running configure. I also added support for executing autogen.sh if it is present.
Example to reproduce the issues. It occurs when building MPC using the most recent version of each library as available today.
```
load("@rules_foreign_cc//tools/build_defs:configure.bzl", "configure_make")
configure_make(
name = "gmp",
lib_source = "@gmp//:all",
shared_libraries = ["libgmp.so"],
static_libraries = ["libgmp.a"],
)
configure_make(
name = "mpfr",
lib_source = "@mpfr//:all", …
```
=> Support running autogen.sh and autoreconf

tools/build_defs/configure_script.bzl
I am cross-compiling Envoy and for some reason hitting a case where `LDFLAGS` is not set. I don't quite understand the root cause yet, but clearly this code shouldn't assume that `vars`  has `LDFLAG` key set to something, especially because it's set conditionally in the first place:
https://github.com/bazelbuild/rules_foreign_cc/blob/74b146dc87d37baa1919da1e8f7b8aafbd32acd9/tools/build_defs/configure_script.bzl#L144-L147
=> Handle case where LDFLAGS is undefined

examples/examples_repositories.bzl
mpfr no longer supports 4.0.2 on the official site, so BazelCI was failing.
=> Update mpfr to 4.1.0

README.md, examples/build_make_itself/BUILD, for_workspace/BUILD, for_workspace/make_build.bzl, for_workspace/repositories.bzl, tools/build_defs/BUILD, tools/build_defs/cmake.bzl, tools/build_defs/configure.bzl, tools/build_defs/framework.bzl, tools/build_defs/make.bzl, tools/build_defs/native_tools/BUILD, tools/build_defs/native_tools/tool_access.bzl, workspace_definitions.bzl
This change adds a new toolchain type, `make_toolchain`. I have also added an implementation that uses the pre-installed toolchain (no shipped `make` yet, will add that shortly too.)
The goal is to use the `make` binary path provided by the toolchain. This way, one can configure a custom toolchain that, for example, runs `emmake make` instead of `make`, to target Emscripten. (At least this is my use case). Another use case is to use a vendored Make, instead of relying on the system `make` binary in the execution environment.
TODO:
Fixes #372.
=> Add a GNU Make toolchain

README.md, tools/build_defs/cc_toolchain_util.bzl, tools/build_defs/framework.bzl
See https://github.com/bazelbuild/bazel/issues/10860.
=> Migrate to modern linking input API.

examples/docs/README.md, tools/build_defs/boost_build.bzl, tools/build_defs/cmake.bzl, tools/build_defs/configure.bzl, tools/build_defs/framework.bzl, tools/build_defs/make.bzl
This makes it possible for stardoc to render information about the rules in this project.
=> Moved documenting comments into `doc` fields

tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl
This change allows rules_foreign_cc to work on architectures other
than x86_64.
Bug: bazelbuild/bazel#11628
Test: manual. no longer fails with "ln: illegal option -- t" on darwin_arm64
=> toolchain_mappings: remove unnecessary arch constraints

examples/examples_repositories.bzl
Version 6.2.0 is gone from gmplib.org.
Also update extension to `.xz`, apparently `.gz` files are no longer being distributed.
=> Update GMP to 6.2.1

examples/BUILD, toolchains_examples/BUILD, tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl
The former has been deprecated and will break by `--incompatible_use_platforms_repo_for_constraints`, as announced in
https://github.com/bazelbuild/bazel/issues/8622.
Fixes #354.
=> Replace references to @bazel_tools//platforms with @platforms//

cc_configure_make/def.bzl
Since this has been unmaintained for a long time (last meaningful commit was 5fda9e82bdbb6d19c7d5e13fb3119a53436e4bd7) it should be removed.
=> Added deprecation notice to `//cc_configure_make:def.bzl`

tools/build_defs/framework.bzl
Otherwise if I put anything in additional_tools I get an error about
depset not being iterable.
This matches the for loop just above, which does the to_list conversion.
=> Expand depset to list

.bazelci/config.yaml, docs/README.md, examples/BUILD, examples/cmake_with_data/BUILD, examples/cmake_with_data/cmake_with_data.txt, examples/cmake_with_data/lib_a/BUILD, examples/cmake_with_data/lib_a/CMakeLists.txt, examples/cmake_with_data/lib_a/src/CMakeLists.txt, examples/cmake_with_data/lib_a/src/lib_a.cpp, examples/cmake_with_data/lib_a/src/lib_a.h, examples/cmake_with_data/lib_b/BUILD, examples/cmake_with_data/lib_b/src/lib_b.cpp, examples/cmake_with_data/lib_b/src/lib_b.h, examples/cmake_with_data/tests/test_cmake_with_data.cpp, examples/cmake_with_data/tests/test_cmake_with_shared_lib.cpp, tools/build_defs/framework.bzl
This adds a [`data`](https://docs.bazel.build/versions/master/be/common-definitions.html#typical-attributes) attribute to rules rules built on `framework.bzl` (`boost_build`, `cmake_external`, `configure_make`, and `make`).
Examples have been added to `@rules_foreign_cc_tests//cmake_with_data/...`
Note, the `@rules_foreign_cc_tests//cmake_with_data:test_with_data` examples will not pass without [--enable_runfiles](https://docs.bazel.build/versions/master/command-line-reference.html#flag--enable_runfiles) enabled. This will need to be explicitly set on windows machines
=> Added `data` attr to common framework

examples/BUILD, examples/cmake_crosstool/static/BUILD, examples/cmake_hello_world_lib/binary/BUILD, examples/cmake_hello_world_lib/shared/BUILD, examples/cmake_hello_world_lib/static/BUILD, examples/cmake_hello_world_variant/BUILD, examples/cmake_synthetic/BUILD, examples/configure_gnuplot/BUILD, test/BUILD, tools/build_defs/shell_toolchain/toolchains/toolchain_mappings.bzl
This is a follow up to https://github.com/bazelbuild/rules_foreign_cc/pull/427
=> Updated uses of `@bazel_tools//src/conditions` to `@platforms//`

WORKSPACE, examples/WORKSPACE, examples/cc_configure_make/BUILD, examples/cmake/BUILD, examples/cmake_android/BUILD, examples/cmake_cares/BUILD, examples/cmake_crosstool/BUILD, examples/cmake_crosstool/static/BUILD, examples/cmake_crosstool/tools/arm_compiler/BUILD, examples/cmake_hello_world_lib/shared/BUILD, examples/cmake_hello_world_lib/static/BUILD, examples/cmake_nghttp2/BUILD, examples/cmake_synthetic/BUILD, examples/cmake_synthetic/liba/BUILD, examples/cmake_synthetic/libb/BUILD, examples/cmake_with_bazel_transitive/BUILD, examples/cmake_working_dir/BUILD, examples/configure_gnuplot/BUILD, examples/configure_libunwind/BUILD, examples/configure_mpc/BUILD, examples/configure_with_bazel_transitive/BUILD, examples/deps/deps_android.bzl, examples/deps/deps_jvm_external.bzl, examples/deps/repositories.bzl, examples/simple_make/BUILD, examples/use_malloc/BUILD, tools/build_defs/cmake.bzl
This should prevent the dependencies in the root workspace from becoming outdated (which they were).
This also adds `rules_cc` and `rules_android` repositories to the examples. Buildifier will now no longer alter files with the `-lint=fix` mode enabled but the repo is still not Buildifier compliant.
=> Moved example dependencies into loadable bzl files

.bazelci/config.yaml, README.md, examples/BUILD, examples/cmake_crosstool/static/BUILD, examples/cmake_hello_world_lib/binary/BUILD, examples/cmake_hello_world_lib/shared/BUILD, examples/cmake_hello_world_lib/static/BUILD, examples/cmake_hello_world_variant/BUILD, examples/cmake_synthetic/BUILD, examples/configure_gnuplot/BUILD, test/BUILD
This adds new builds to CI to test the root of the repo as well as the examples. Among those new builds are two checks for the minimum supported Bazel version.
In the future it might be better to consolidate all these tests into smaller tests cases such that we only have jobs for testing the root, examples, and docs directories. But I think making sure everything is being tested is a better place to be in.
=> Add tests for checking the minimum supported version to CI

tools/build_defs/configure.bzl, tools/build_defs/configure_script.bzl
We have run into a library that works with autoconf (jemalloc) but not autoreconf.
As such, I've introduced a new rule to use autoconf as the build script.
=> configure: add autoconf to configure

examples/cmake_with_data/lib_b/BUILD, examples/cmake_with_data/tests/test_cmake_with_shared_lib.cpp
supports_dynamic_linker feature was removed from cc toolchain for macOS,
cc_binary should be used to build shared library.
Context: bazelbuild/bazel#4341 (comment)
=> Fix test target on macOS with Bazel@HEAD

.gitignore, examples/cmake_working_dir/BUILD, examples/cmake_working_dir/source_root/.keep, test/BUILD, test/detect_root_test/BUILD, test/detect_root_test/WORKSPACE, test/detect_root_test/expected/out_fg.txt, test/detect_root_test/expected/out_repo.txt, test/expected/out_symlinked_dirs.txt, test/expected/out_symlinked_dirs_osx.txt, tools/build_defs/detect_root.bzl
This fixes some inconsistent behavior I was seeing in how the source root was detected. Using `exclude_directories=0` on [glob](https://docs.bazel.build/versions/master/be/functions.html#glob) returns incorrect results in that directories will have [File.is_source](https://docs.bazel.build/versions/master/skylark/lib/File.html#is_source) set to `True`. This should be `False` and [File.is_directory](https://docs.bazel.build/versions/master/skylark/lib/File.html#is_directory) should be `True` instead.
The original implementation seems to have been introduced in https://github.com/bazelbuild/rules_foreign_cc/pull/57 and seemed to try and account for the use of `exclude_directories=0` without the correct [File.is_directory](https://docs.bazel.build/versions/master/skylark/lib/File.html#is_dire …
=> Fixed incorrect detection of lib_source root

.bazelci/config.yaml, examples/cmake_defines/BUILD, examples/cmake_defines/lib_a/CMakeLists.txt, examples/cmake_defines/lib_a/lib_a.cpp, examples/cmake_defines/lib_b/CMakeLists.txt, test/standard_cxx_flags_test/tests.bzl, tools/build_defs/cc_toolchain_util.bzl
(Hopefully) Addresses issue highlighted in #301.
I suspect there are similar issues in propagating includes from deps `CcInfo.compilation_context`.
=> Propagate defines into CFLAGS and CXXFLAGS passed to the framework

tools/build_defs/framework.bzl
Having the version in the generated script will cause cache invalidations any time the version number is bumped even if the change causing the version bump doesn't affect the build being executed.
=> Remove version from generated script

tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl
Hey thanks for this project, it's amazing.
I recently had `configure_make` builds fail on macOS, but the logs showed the compile was successful. I tracked the bug down to the generated shell script, which was throwing an error on copying the results.
There was a slight error with the bash syntax, a local variable was being created *and* expanded at the same time, but this fails as the variable doesn't yet exist.
Removing this variable expansion fixed my builds.
Something like `set -o nounset` or `set -e` would've caught this, but I wasn't confident enough with my bash skills to add that here, out of fear of causing errors elsewhere.
=> Fix failing configure_make builds on macOS

tools/build_defs/framework.bzl
This is the similar change to https://github.com/bazelbuild/rules_foreign_cc/pull/481. Shout outs to @scele 😄
=> Remove a print from the cleanup function

test/expected/inner_fun_text.txt, test/expected/inner_fun_text_osx.txt, tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
closes https://github.com/bazelbuild/rules_foreign_cc/issues/505
- 0122473a8c59682a193427f5589ebf772e5fb57e fixes some unbound variables. This change is proven by the change in between [this build](https://buildkite.com/bazel/rules-foreign-cc/builds/1761#83c5581e-433d-40d2-a8ee-a5a245dd2bb3) and [this build](https://buildkite.com/bazel/rules-foreign-cc/builds/1764#8fb42e4c-6e09-4254-b48a-aecf111f42c2) where this change was cherry picked and fixed an error
- f9f230385cbcf2e854304815c44ccca4447d5f4b fixes recursive symlink issues on macos. This change is proven by the change in behavior between [this build](https://buildkite.com/bazel/rules-foreign-cc/builds/1764#0e264415-91c9-47dc-a721-3296d472607c) and [this build](https://buildkite.com/bazel/rules-foreign-cc/builds/1765#4ebd633f-e873-4c39 …
=> Fixed unbound variable in commands and recursive symlinks

tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
This removes the dependency on autotools for projects such as "make",
where autotools are only invoked if the timestamp of certain files has
changed.
=> Preserve timestamps in copy_dir_contents_to_dir

tools/build_defs/framework.bzl
This is a slight cleanup and does not appear as though it'd have a negative impact on users since all the same data will be made available to the relevant [run_shell](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run_shell) command
=> Pass cc_toolchain files as tools instead of inputs

tools/build_defs/configure_script.bzl, tools/build_defs/framework.bzl, tools/build_defs/shell_toolchain/toolchains/impl/default_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/linux_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/osx_commands.bzl, tools/build_defs/shell_toolchain/toolchains/impl/windows_commands.bzl
This PR cleans up the error outputs so they're reasonably parseable. This is done by replacing the use of [ctx.actions.run_shell](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run_shell) with [ctx.actions.run](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run) in the core framework and instead writing the code to a file.
Windows is a bit unique in that it also builds a `.bat` script to wrap the `.sh` script and, like Bazel ([Using Bazel without Bash msys2](https://docs.bazel.build/versions/3.5.0/windows.html#using-bazel-without-bash-msys2)), it expects bash to be available on the host.
One other notable change here is that the `echo` alias is now actually `echo` and no longer `printf`. This significantly cleans up the code required for formatting …
=> Reduce noise in build logs

README.md, docs/README.md, docs/docs.bzl, examples/cmake_android/BUILD.bazel, examples/cmake_crosstool/BUILD.bazel, examples/cmake_crosstool/static/BUILD.bazel, examples/cmake_defines/BUILD.bazel, examples/cmake_hello_world_lib/binary/BUILD.bazel, examples/cmake_hello_world_lib/shared/BUILD.bazel, examples/cmake_hello_world_lib/static/BUILD.bazel, examples/cmake_hello_world_variant/BUILD.bazel, examples/cmake_synthetic/BUILD.bazel, examples/cmake_with_bazel_transitive/BUILD.bazel, examples/cmake_with_data/BUILD.bazel, examples/cmake_working_dir/BUILD.bazel, examples/third_party/cares/BUILD.cares.bazel, examples/third_party/curl/BUILD.curl.bazel, examples/third_party/libgit2/BUILD.libgit2.bazel, examples/third_party/libpng/BUILD.libpng.bazel, examples/third_party/libssh2/BUILD.libssh2.bazel, examples/third_party/pcre/BUILD.pcre.bazel, examples/third_party/zlib/BUILD.zlib.bazel, tools/build_defs/cmake.bzl
This makes the naming conventions of the rules more consistent.
Note that the previous name of `cmake_external` continues to work.
=> Renamed `cmake_external` to `cmake`

README.md, docs/README.md, examples/cmake_crosstool/BUILD.bazel, examples/cmake_crosstool/static/BUILD.bazel, examples/cmake_defines/BUILD.bazel, examples/cmake_hello_world_lib/binary/BUILD.bazel, examples/cmake_hello_world_lib/shared/BUILD.bazel, examples/cmake_hello_world_lib/static/BUILD.bazel, examples/cmake_hello_world_variant/BUILD.bazel, examples/cmake_with_bazel_transitive/BUILD.bazel, examples/cmake_with_data/BUILD.bazel, examples/configure_use_malloc/BUILD.bazel, examples/make_simple/BUILD.bazel, examples/ninja_simple/BUILD.bazel, examples/third_party/bison/BUILD.bison.bazel, examples/third_party/cares/BUILD.cares.bazel, examples/third_party/curl/BUILD.curl.bazel, examples/third_party/gn/BUILD.gn.bazel, examples/third_party/iconv/BUILD.iconv.bazel, examples/third_party/libgit2/BUILD.libgit2.bazel, examples/third_party/libpng/BUILD.libpng.bazel, examples/third_party/libssh2/BUILD.libssh2.bazel, examples/third_party/openssl/BUILD.openssl.bazel, examples/third_party/pcre/BUILD.pcre.bazel, examples/third_party/zlib/BUILD.zlib.bazel, tools/build_defs/framework.bzl
This clears up some confusion I've seen users run into by renaming some attributes
| old                 | new                |
| ------------------- | ------------------ |
| binaries            | out_binaries       |
| headers_only        | out_headers_only   |
| interface_libraries | out_interface_libs |
| shared_libraries    | out_shared_libs    |
| static_libraries    | out_static_libs    |
Note that the old attributes are still supported for a short while longer so users can comfortably transition.
=> Prefixed all output attributes with `out_` to make their use clearer

README.md, WORKSPACE, docs/WORKSPACE.bazel, docs/docs.bzl, examples/WORKSPACE, examples/cmake_crosstool/WORKSPACE, examples/configure_use_malloc/WORKSPACE, examples/third_party/WORKSPACE.bazel, examples/toolchains_examples/WORKSPACE.bazel, foreign_cc/repositories.bzl, test/standard_cxx_flags_test/WORKSPACE, workspace_definitions.bzl
This solves for some bzl visibility issues and brings the repo into alignment with other rules
- [rules_rust](https://bazelbuild.github.io/rules_rust/#setup)
- [rules_swift](https://github.com/bazelbuild/rules_swift#2-configure-your-workspace)
=> Moved `workspace_definitions.bzl` to `foreign_cc/repositories.bzl` 

foreign_cc/make.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/make_script.bzl
All of the functionality for generating a build script for the `make` rule was in the same file which generates the `configure_make` build script. There was minimal overlap between the two and the majority of the functionality in `configure_script.bzl` was for generating a `make` script. To make the two code paths clearer, `make_script.bzl` has been created and now contains functionality for building the relevant make script and is the owner for shared macros still used in `configure_script.bzl`.
=> Moved `make` script creation into it's own file

foreign_cc/built_tools/cmake_build.bzl, foreign_cc/built_tools/make_build.bzl, foreign_cc/built_tools/ninja_build.bzl, foreign_cc/built_tools/private/BUILD.bazel, foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/private/framework.bzl, toolchains/BUILD.bazel
To prevent massive text dumps when building "built tool" toolchains, all built tool rules now share a common framework similar to the other rules in `//foreign_cc:defs.bzl`.
Some notable changes:
- each built tool rule has had it's `*_srcs` attribute renamed to `srcs`. So for `ninja_tool`, `ninja_srcs` must now be passed to `srcs`.
- While this isn't a change, built tool rules will not fail if the tool fails to build or install for whatever reason. https://github.com/bazelbuild/rules_foreign_cc/pull/548 is a PR for addressing this issue.
=> Added a common framework for built tools

.bazelci/config.yaml, toolchains/BUILD.bazel
Windows binaries all have the `.exe` extension so the path should reflect this
Additionally, the `ninja_tool` builds the binary in the root of the install directory, This should be corrected but for now this PR simply ensures the toolchain has the correct path to the ninja binary.
Finally, this PR raises the min tested Bazel version to `3.7.0`
=> Fixed incorrect tool paths for windows

foreign_cc/private/framework.bzl, foreign_cc/private/shell_toolchain/toolchains/impl/macos_commands.bzl
We should be using the modern name. This also matches Bazel's [platform](https://github.com/bazelbuild/platforms/blob/ed46070dfc79646c573acede7c4f9257d3d8fe44/os/BUILD#L54-L63) definitions
=> Update the macos `os_name` from `osx` to `macos`

.bazelci/config.yaml, examples/cmake_with_target/BUILD.bazel, examples/cmake_with_target/src/CMakeLists.txt, examples/cmake_with_target/src/lib.cpp, examples/cmake_with_target/src/lib.h, foreign_cc/cmake.bzl
Targets can now be properly passed to the CMake build command and arguments are now appropriately the last thing to be passed to provide the most flexibility.
=> Fixed cmake build and target arguments

foreign_cc/built_tools/private/built_tools_framework.bzl
Now that the cmake rule only requires a make binary when it's going to be used, we can re-enable error checking for the built tools framework.
=> Enabled error checking in the built_tools framework

foreign_cc/private/shell_toolchain/toolchains/impl/default_commands.bzl, foreign_cc/private/shell_toolchain/toolchains/impl/linux_commands.bzl, foreign_cc/private/shell_toolchain/toolchains/impl/windows_commands.bzl
If the file being copied is owned by a different user than the build
action, which may be the case for some remote execution platforms,
`cp -p` fails with `EPERM` whereas `touch -r` won't.
=> Use touch not cp -p to preserve timestamps

foreign_cc/private/detect_root.bzl
detect_root and filter_containing_dirs_from_inputs showed up on profiles of our builds as taking a long time (300+ ms). This change uses faster algorithms for detecting the root from a set of source files and eliminating duplicates.
The root is the shortest common dirname among all files. There is an implicit assumption that there is at least one file at the root, otherwise in a tree like the following, the wrong root will be detected, but the existing code also makes this assumption and it seems like it's required.
```
foo/bar/bar.c
foo/baz/baz.c
(Root should be foo, but will be detected as foo/bar)
```
filter_containing_dirs_from_inputs is made faster by avoiding the sort of a potentially large number of files by doing two passes, first to collect a set of directories that contain …
=> Optimize methods in detect_root.bzl

foreign_cc/private/shell_toolchain/toolchains/impl/macos_commands.bzl
sed on macOS requires a suffix when using -i. Current usage will create temporary files with -e suffixes so pass an empty suffix to avoid creating the backup files on macOS.
=> Pass empty suffix to sed on macOS

.github/workflows/stale.yaml
Inspired by https://github.com/bazelbuild/rules_python/pull/454, it'd be great if we had the resources to get to everything but unfortunately we do not. This bot should help us focus on current/popular requests from the community and help drive the project forward.
=> Add configuration for stale bot

foreign_cc/private/cmake_script.bzl, foreign_cc/private/framework.bzl, test/cmake_text_tests.bzl
This moves more functionality into the framework so things like https://github.com/bazelbuild/rules_foreign_cc/issues/607 are more doable. Instead of relying on bash, we should use the foreign_cc framework to define functionality.
=> Replaced uses of `$var ` with `$$var$$`

foreign_cc/boost_build.bzl, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/make.bzl, foreign_cc/ninja.bzl
As per https://github.com/bazelbuild/bazel/issues/11584 add `incompatible_use_toolchain_transition` attribute to enable use of `exec` configuration
=> Add incompatible_use_toolchain_transition = True 

foreign_cc/built_tools/make_build.bzl, foreign_cc/built_tools/ninja_build.bzl, foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/framework/BUILD.bazel, foreign_cc/private/framework/helpers.bzl, foreign_cc/private/framework/platform.bzl, foreign_cc/private/framework/toolchains/commands.bzl, foreign_cc/private/framework/toolchains/linux_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl, test/convert_shell_script_test.bzl
I don't think this is something that should live in the foreign_cc toolchain. Ideally this would be replaced by something provided by Bazel but until then I like having it separated
=> Added a new `platform_info` target to the foreign_cc framework

foreign_cc/private/framework/toolchains/linux_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl, test/expected/inner_fun_text.txt, test/expected/inner_fun_text_macos.txt
In investigating build failures brought up in https://github.com/bazelbuild/rules_foreign_cc/pull/622 I uncovered some messages in the build logs:
```
sed: /private/var/tmp/_bazel_user/2d7cc63c99a1f0f43d4f45bc36f2be85/sandbox/darwin-sandbox/423/execroot/rules_foreign_cc_examples_third_party/bazel-out/host/bin/external/subversion/subversion.ext_build_deps/apr/lib/libapr-1.la: in-place editing only works for regular files
```
I found out that `sed` is unable to update paths that are symlinks. It requires a path to a real file.
We currently only have one use of `sed` and it's to update paths files which contain absolute paths to the current sandbox.
https://github.com/bazelbuild/rules_foreign_cc/blob/b8b88cd2d16035aa1639434eb808f4d67a34d5ae/foreign_cc/private/framework/toolchains/linux_comman …
=> Fixed silent failures replacing sandbox paths in outputs

foreign_cc/configure.bzl, foreign_cc/private/configure_script.bzl
Rework of patch in #549. Fixes #590.
=> Set MAKE env var

foreign_cc/private/framework.bzl
This fixes the bug introduced in #556 so that the `make_commands` are built from `attrs`, not `ctx.attr`.
=> Build make commands from correct attribute dict

foreign_cc/BUILD.bazel, foreign_cc/private/framework.bzl
We should only be generating what we need or intend to output. This empty file we create is not needed. Instead, we can achieve the same behavior only using the copy directory that's created.
=> Remove the need to always generate an empty file

foreign_cc/private/framework/toolchains/linux_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl, test/expected/inner_fun_text.txt, test/expected/inner_fun_text_macos.txt
This reverts commit 08598910609153bb82c7e3a91dbf7ae3d17a0575. (#644)
=> Revert "Include `libtool` and `.nice` files when replacing sandbox paths (#644)"

foreign_cc/private/framework.bzl
The primary intent of this change is to have a more structured way of controlling the environment. The way it's currently implemented adds support for [--action_env](https://docs.bazel.build/versions/master/command-line-reference.html#flag--action_env) to MacOS platforms and adds a centralized place in code to manage environment variables.
=> Restrict use of `use_default_shell_env` to windows.

docs/docs.bzl, foreign_cc/private/framework.bzl, foreign_cc/providers.bzl
This renames the following:
- `ForeignCcArtifact` -> `ForeignCcArtifactInfo`
- `ForeignCcDeps` -> `ForeignCcDepsInfo`
=> Fixed naming convention issues in common providers

.bazelci/config.yaml, .pre-commit-config.yaml, CONTRIBUTING.md, examples/cmake_crosstool/compilers/linaro_linux_gcc_5.3.1.BUILD
Matches the one just landed in rules_apple: https://github.com/bazelbuild/rules_apple/commit/61bc7c01aeee1324dc276e4f09bba88913ab2a62
Note, surprisingly the build for main is green for buildifier
https://buildkite.com/bazel/rules-foreign-cc/builds/2745#e13d8907-77a6-46a7-851c-d3ca17eee8dd
even though this one file touched in this PR needed formatting :shrug:
=> chore: setup a buildifier pre-commit hook

examples/third_party/libjpeg_turbo/BUILD.libjpeg_turbo.bazel
It helps if we actually return the correct library 😅
While `libjpeg` is being created, the target we're interested in is `libjpeg_turbo`.
=> Fixed libjpeg turbo example

examples/make_simple/BUILD.bazel, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/make.bzl, foreign_cc/ninja.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/framework.bzl
This adds the `tool_prefix` and `build_data` attribute and deprecates `additional_tools`, `additional_inputs`, and `tool_deps`.
`tool_prefix` is expected to solve for issues brought up in https://github.com/bazelbuild/rules_foreign_cc/pull/671#issuecomment-858932271
Basically, some uses of build tools must be prefixed by things like `emcmake` and `emmake` for [emscripten](https://emscripten.org/). These toolchains should be provided as `build_data` and consumed in `tool_prefix` using [make variable expansion](https://docs.bazel.build/versions/main/be/make-variables.html#predefined_label_variables)
=> Added `tool_prefix` attribute

examples/third_party/apr/BUILD.apr.bazel, examples/third_party/apr/BUILD.bazel, examples/third_party/apr/apr_repositories.bzl, examples/third_party/apr/macos_iovec.patch, examples/third_party/apr/macos_pid_t.patch, examples/third_party/apr_util/BUILD.apr_util.bazel, examples/third_party/apr_util/BUILD.bazel, examples/third_party/apr_util/apr_util_repositories.bzl, examples/third_party/repositories.bzl, examples/third_party/sqlite/BUILD.bazel, examples/third_party/sqlite/BUILD.sqlite.bazel, examples/third_party/sqlite/sqlite_repositories.bzl, examples/third_party/subversion/BUILD.bazel, examples/third_party/subversion/BUILD.subversion.bazel, examples/third_party/subversion/subversion_repositories.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/framework/toolchains/commands.bzl, foreign_cc/private/framework/toolchains/linux_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl, foreign_cc/private/make_script.bzl
This change expands on the `define_absolute_paths` and `replace_absolute_paths` functionality which replace absolute paths to files within `EXT_BUILD_DEPS` with that environment variable to be expanded at a later time and introduces `define_sandbox_paths` and `replace_sandbox_paths` which more generally replaces absolute paths to the exec root with `${EXT_BUILD_ROOT}`. In both cases, these variables are update at the beginning of each build and are otherwise invisible to foreign build systems.
=> Added support for replacing sandbox paths in build artifacts

foreign_cc/cmake.bzl, foreign_cc/private/cmake_script.bzl, test/cmake_text_tests.bzl
Set the prefix before the first CMake invocation (where all the extra flags are passed), and don't set the prefix for the `--build` and `--install` invocations of CMake.
Fixes #685.
=> Fix tool_prefix for CMake

foreign_cc/private/framework.bzl
This PR modifies the progress message that is printed to console when building targets using `rules_foreign_cc`. Previously, the progress message would be of the (somewhat confusing) form:
```
CcConfigureMakeRule external/openssl/openssl/include
```
This PR modifies the message to be of the form:
```
Building openssl (Foreign Cc - Configure)
```
=> Set progress message when building targets

.bazelci/config.yaml
Ubuntu 16.04 is end-of-life, we're going to remove it from Bazel CI.
=> Remove ubuntu1604 from presubmit.yml

foreign_cc/repositories.bzl, toolchains/BUILD.bazel, toolchains/toolchains.bzl
The introduction of the new `nmake` toolchain should not impact anyone unless they're using a custom platform which defines the `@bazel_tools//tools/cpp:msvc` constraint.
=> Added a `make_toolchain`, `nmake` for `msvc` windows platforms

examples/cmake_synthetic/test_libb.cpp, examples/cmake_with_bazel_transitive/test_libb.cpp, examples/cmake_with_data/lib_a/src/lib_a.cpp, examples/cmake_with_data/tests/test_cmake_with_data.cpp, examples/cmake_with_data/tests/test_cmake_with_shared_lib.cpp, examples/cmake_working_dir/test_liba.cpp, examples/third_party/cares/c-ares-test.cpp
The compilers in CI are reasonably old and aren't strict at requiring the correct headers included for classes defined in std. This adds the missing include headers that are needed to be standards compliant when using the exception `std::runtime_error`
=> Add missing includes for std::runtime_error

foreign_cc/private/cc_toolchain_util.bzl
This overcomes bugs in MSYS2 where leading slashes are converted to
paths, e.g. "/nologo" is converted to "C:\msys64\nologo".
This commit would modify the flag to become "-nologo". MSVC supports
both slashes and dashes for flags.
=> Convert MSVC flags by replacing slashes with dashes

examples/configure_with_bazel_transitive/simple_lib/configure, foreign_cc/private/configure_script.bzl
This change is required when using the MSVC toolchain on Windows,
as paths for tools such as the compiler contain whitespaces (e.g.
C:\Program Files\...)
=> Wrap tool paths that contain whitespaces in quotes

foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/defs.bzl, foreign_cc/make.bzl, foreign_cc/private/transitions.bzl, foreign_cc/repositories.bzl, toolchains/BUILD.bazel, toolchains/toolchains.bzl
The macros utilise bazel "transitions" to set the `make` toolchain to
be the preinstalled `nmake` tool.
Note that the msvc constraint was removed from the
`exec_compatible_with` attribute of `preinstalled_nmake_toolchain` as
the condition is not actually met even when building with msvc. See
https://github.com/bazelbuild/bazel/issues/7730.
This will be tested in PR #729
=> Add <rule>_variant macros

examples/BUILD.bazel, examples/third_party/BUILD.bazel, examples/third_party/curl/BUILD.bazel, examples/third_party/curl/BUILD.curl.bazel, examples/third_party/curl/curl_test.cc, examples/third_party/openssl/BUILD.bazel, examples/third_party/openssl/BUILD.nasm.bazel, examples/third_party/openssl/BUILD.openssl.bazel, examples/third_party/openssl/BUILD.perl.bazel, examples/third_party/openssl/openssl_repositories.bzl, examples/third_party/openssl/openssl_test.cc, foreign_cc/private/framework.bzl
This PR modifies rules_foreign_cc so that OpenSSL successfully builds using the MSVC toolchain on Windows.
Note that I started working on this branch before the recent commit on master whereby the `nmake` toolchain was added. I instead added an `nmake` attribute to the `configure_make()` rule. It would be good to get the reviewers' thoughts on which approach is best
=> Build OpenSSL using MSVC toolchain on Windows

examples/cmake_defines/BUILD.bazel, examples/cmake_defines/nocrosstool/BUILD.bazel, foreign_cc/private/cmake_script.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/framework/helpers.bzl, test/cmake_text_tests.bzl
Previously the cmake rule was incorrectly attempting to quote the toolchain flags as they are passed into a HEREDOC in the generated bash script.
This updates the generated bash script to use local variables to pass the flags through to the CMake crosstool file generated by the HEREDOC to avoid having to escape certain characters in those strings. This approach was chosen over disabling expansion in the HEREDOC because it is still desirable to expand some environment variables within the HEREDOC to e.g. access paths for dependencies.
=> Fix quoting of toolchain flags passed to cmake

foreign_cc/make.bzl
When using a make variant, such as NMake, bazel would print "GNUMake - Building ..." to console. To avoid confusion, this commit removes the GNU prefix.
=> Remove "GNU" prefix to Make

.bazelci/config.yaml
The changes here unblock other PRs while a resolution is worked on in https://github.com/bazelbuild/continuous-integration/issues/1204
=> Temporarily disable broken windows targets

examples/third_party/BUILD.bazel, examples/third_party/apr_util/BUILD.apr_util.bazel, examples/third_party/apr_util/BUILD.expat.bazel, examples/third_party/apr_util/apr_util_repositories.bzl
The build of apr_util would previously fail if expat libs and headers were not preinstalled in the build environment.
Resolves #750
=> Add expat dep to apr_util build

examples/BUILD.bazel, examples/third_party/apr/BUILD.apr.bazel, examples/third_party/apr_util/BUILD.expat.bazel, examples/third_party/curl/BUILD.bazel, examples/third_party/openssl/BUILD.bazel, examples/third_party/openssl/BUILD.openssl.bazel
These dependencies are not intended to be loaded through `rules_foreign_cc_examples` so moving these config flags into the BUILD files themselves should make the targets more snapshot-able.
=> Move more example build config into example BUILD files

foreign_cc/private/framework.bzl
This allows passing all the usual tags to the underlying run_shell action, such as 'no-sandbox', 'no-cache', etc. https://docs.bazel.build/versions/main/be/common-definitions.html#common.tags
=> Pass all tags to execution_requirements

examples/WORKSPACE.bazel, examples/third_party/BUILD.bazel, examples/third_party/WORKSPACE.bazel, examples/third_party/cares/BUILD.bazel, foreign_cc/private/framework.bzl
Some projects like envoy-mobile use rules_foreign_cc to build targeting
iOS, so this is useful to validate on CI as part of the macOS test
build. This also fixes a bug where this was broken since 
c41020e4655fc9adb4bad7e9c04a3f2cf2cc9250 because the wrong SDKROOT was used
=> Fix building for iOS

foreign_cc/private/framework.bzl
Certain (C)Make projects (such as [AFL++](https://github.com/AFLplusplus/AFLplusplus)) emit binaries that are symlinks to other emitted binaries. When built with `rules_foreign_cc`, this can lead to non-deterministic dangling symlink errors since Bazel visits the outputs in an unspecified order. This is fixed by resolving symlinks among the emitted binaries, just like it is already done for libraries.
=> Resolve symlinks among output binaries

foreign_cc/private/framework.bzl
If something is misconfigured in your setup, these commands can fail.
Example:
```
xcodebuild: error: SDK "iphonesimulator14.4" cannot be located.
xcodebuild: error: SDK "iphonesimulator14.4" cannot be located.
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator14.4
```
In this case, because the execution of the command, and the `export`,
were in the statement, bash ignores the exit code. This breaks that up.
We could also break this up with:
```
foo=$(...)
export foo
```
But that doesn't work in the postprocessing currently done with exports.
=> Improve failed exports logic

foreign_cc/private/cc_toolchain_util.bzl, test/standard_cxx_flags_test/BUILD.bazel, test/standard_cxx_flags_test/tests.bzl
Without this commit, the copts and linkopts attributes on rules such as make and cmake did not actually add any flags to the foreign build system.
This is similar to https://github.com/bazelbuild/rules_foreign_cc/pull/777 and another place where, as far as I can tell, user-supplied flags were silently swallowed. `copts` is being used in https://github.com/bazelbuild/rules_foreign_cc/blob/a7105dafb067c785cc9ade2c70b0d0ce967490fc/foreign_cc/private/cc_toolchain_util.bzl#L224 but that function always returns an empty dictionary for me. @UebelAndre Do you know how this relates to https://github.com/bazelbuild/rules_foreign_cc/blob/a7105dafb067c785cc9ade2c70b0d0ce967490fc/foreign_cc/private/cc_toolchain_util.bzl#L287 which seems much more feature complete?
=> Add flags from copts and linkopts attributes

foreign_cc/make.bzl
configure_make already used BUILD_TMPDIR whereas make did not.
Fixes #797.
=> Let make build in BUILD_TMPDIR

examples/make_simple/BUILD.bazel, examples/make_simple/code/BUILD.bazel, examples/make_simple/code/Makefile, examples/make_simple/code/cxx_wrapper.sh, examples/make_simple/code/liba.cpp, examples/make_simple/code/liba.h, examples/make_simple/test_libb.cpp, foreign_cc/make.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/configure_vars.bzl, foreign_cc/private/make_env_vars.bzl, foreign_cc/private/make_script.bzl
=> Pass toolchain and user env variables to make invocation

foreign_cc/built_tools/make_build.bzl, foreign_cc/private/cc_toolchain_util.bzl, toolchains/built_toolchains.bzl, toolchains/make-reproducible-bootstrap.patch
Uses the Bazel C/C++ toolchain to bootstrap make and ensure that the
resulting binary contains no absolute and thus non-hermetic paths.
Building make reproducibly helps with remote caching and removes the
dependency on a C compiler installed on the host.
=> Bootstrap make reproducibly

foreign_cc/private/framework.bzl
This should help support foreign inclusion of libraries that export their headers at multiple locations.
In particular, this should help with libraries where the headers reference each other by locations that don't match the only valid `out_include_dir`.
=> Support propagation of `includes`

examples/cmake_with_data/tests/test_cmake_with_shared_lib.cpp
As of https://github.com/bazelbuild/bazel/pull/14369, shared libraries produced with cc_binary on macOS with the auto-configured toolchain use the correct file extension for dynamic libraries (`.dylib` rather than `.so`). This requires adapting a test.
=> Adapt tests to new cc_binary file extension on macOS

foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/repositories.bzl, toolchains/BUILD.bazel, toolchains/native_tools/tool_access.bzl
Add the toolchain types and resolve these to the preinstalled versions of such tools.
Note this only sets up the toolchains and doesn't actually make use of them yet.
=> Add toolchain types for autotools tools

foreign_cc/repositories.bzl
Missed a case due to a merge conflict.
=> Remove call to register_toolchains for bzlmod

foreign_cc/private/framework/helpers.bzl
These loops are essentially while loops and have reasonable exit conditions, so there is no reason to arbitrarily limit the range.
There is precedent for this number at:
https://github.com/bazelbuild/bazel/blob/f802525ad37e4f4567103682244d65f6cc55ff57/src/main/starlark/builtins_bzl/common/cc/experimental_cc_shared_library.bzl#L78
Related to #857
=> Remove arbitrary limits in Starlark "while" loops

foreign_cc/private/make_env_vars.bzl
These variables are already exported in the build script prelude and thus don't have to be set on individual make commands.
Resolves an undesired side effect of https://github.com/bazelbuild/rules_foreign_cc/commit/f61ce5d10b221c643ae48063c3484fadf84066d4, that however should not have resulted in this kind of breakage.
Workaround for #857, the fix for the underlying issue will be submitted as a separate PR.
=> Do not set user defined env variables twice for (c)make

examples/make_simple/BUILD.bazel, examples/make_simple/code/Makefile, examples/third_party/openssl/BUILD.openssl.bazel, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/make.bzl, foreign_cc/ninja.bzl, foreign_cc/private/framework.bzl
This fixes #857 fundamentally by adressing the root cause - `expand_locations` can't be applied to a shell command fragment by itself as it doesn't unescape `$$`.
I divided this PR into individual commits with more detailed commit messages to make the review easier, but feel free to squash them in the end if that's your preferred workflow.
=> Replace `escape_locations` with `escape_locations_and_make_variables` everywhere

examples/third_party/WORKSPACE.bazel, examples/third_party/cares/BUILD.bazel, foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/private/framework.bzl
This fixes a bug where on M1 macOS machines, when building for the
x86_64 iOS simulator, the cmake dependencies were building for arm64
instead, _if_ you had `/usr/sbin` in your `$PATH` used with bazel. The
issue is that cmake calls `/usr/sbin/sysctl` to determine the host
architecture:
https://gitlab.kitware.com/cmake/cmake/-/blob/6453bd046ef23798c64333042d76851f15eff2fc/Modules/Platform/Darwin-Initialize.cmake#L23-41
And then it uses that computed value here if no other archs are set:
https://gitlab.kitware.com/cmake/cmake/-/blob/6453bd046ef23798c64333042d76851f15eff2fc/Source/cmGeneratorTarget.cxx#L3378-3399
As far as I can tell this is a mismatch in expectation between how we
call cmake vs how you would normally call it for cross compilation since
we do not set `CMAKE_SYSTEM_NAME` …
=> Set CMAKE_OSX_ARCHITECTURES to target architecture

examples/WORKSPACE.bazel, examples/third_party/cares/BUILD.bazel
This version of rules_apple comes with the Starlark version of the apple_binary rule, whose native equivalent has been removed from Bazel after 5.1.
As a result, this commit will fix the following breakage on Bazel CI with Bazel @ HEAD:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2442#eca49979-d494-4c9b-921d-3faebd957fa4
=> Upgrade rules_apple to 0.34.0

foreign_cc/built_tools/ninja_build.bzl
macOS 12.3 removed /usr/bin/python, which is what's currently in the
shebang of ninja's configure.py. This forces us to run this with python3
instead.
This can be removed if https://github.com/ninja-build/ninja/pull/2118 is merged
=> Fix ninja bootstrap on macOS 12.3+

examples/WORKSPACE.bazel
rules_apple 0.34.0 is incompatible with Bazel @ HEAD since it does not contain https://github.com/bazelbuild/rules_apple/commit/df98f37ea725005ec8682c9cd582bac74445b689
Consequently, we need to use a newer, yet unreleased version to fix https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2443#7266607a-bd84-4863-abe9-6543530aeed3
Eventually we should wait for a new release and use it instead.
=> Use an unreleased version of rules_apple

foreign_cc/configure.bzl, foreign_cc/make.bzl
The jom tool (a fork of nmake which supports parallel builds) does not
support the "-C dir" arg. Given that the build script generated by
rules_foreign_cc changes the working directory to $BUILD_TMPDIR before
invoking make/nmake/jom, there is no need to add the "-C $BUILD_TMPDIR"
arg. This commit removes the addition of the "-C $BUILD_TMPDIR" arg so
that jom can be used as a make variant.
=> Faciliate usage of jom

WORKSPACE.bazel, foreign_cc/built_tools/make_build.bzl, foreign_cc/built_tools/ninja_build.bzl, foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/repositories.bzl
Use python toolchain when building ninja
This allows for a hermetic build of ninja by using a hermetic python
toolchain, like the one provided by the python_register_toolchains macro
in rules_python.
=> Hermetic ninja build

foreign_cc/private/framework.bzl
Previously, tool runfiles were not present at execution time. For example, if the provided tool was a py_binary, the py_binary would fail to run due to the omission of the runfiles.
This relates to bazelbuild/bazel#10110 and #849
=> Add tool runfiles to action

examples/cmake_hello_world_lib/shared/BUILD.bazel, examples/cmake_hello_world_lib/shared/CMakeLists.txt, foreign_cc/private/framework.bzl, foreign_cc/providers.bzl
C/C++ projects typically install DLLs in the "bin" folder and the
associated interface library in the "lib" folder. This commit changes
the default behaviour accordingly.
The now redundant postfix script in the cmake_hello_world_lib shared test has been removed. The test was also previously broken as no interface library was generated. This commit resolves that issue
=> Add ability to specify DLL dir

.bazelci/config.yaml
Bazel CI recently upgrade the default MSVC version to 2019.  LLVM 11.0.0 is required to work with MSVC 2019, but not yet available on Bazel CI.
=> Ping MSVC version to 2017

foreign_cc/boost_build.bzl
For cross compiling (or other configuration) of boost, we often need to generate a `user-config.jam` file and pass the location of this file as `user_options`. That is why I needed variable expansion of `user_options` parameter of `boost_build`.
```
boost_build(
...
user_options = [
...
"--user-config=$(location :user_config)"
]
)
```
=> Expand variables in `user_options` for boost_build

.bazelci/config.yaml
The examples/cmake_android picks up local instead of Android Cc toolchains.
=> Disable cc toolchain resolution in examples on Mac

examples/current_toolchains/BUILD.bazel, toolchains/native_tools/native_tools_toolchain.bzl, toolchains/toolchains.bzl
See individual commit messages for more info
=> Fix current toolchains

foreign_cc/configure.bzl, foreign_cc/private/configure_script.bzl
Certain configure scripts use a different flag instead of '--prefix', such as
Perl using '-Dprefix='.
=> Add prefix flag config option to make_configure

foreign_cc/ninja.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/framework/toolchains/commands.bzl, foreign_cc/private/framework/toolchains/freebsd_commands.bzl, foreign_cc/private/framework/toolchains/linux_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl, foreign_cc/private/make_script.bzl, test/BUILD.bazel, test/convert_shell_script_test.bzl, test/expected/inner_fun_text.txt, test/expected/inner_fun_text_freebsd.txt, test/expected/inner_fun_text_macos.txt, test/symlink_contents_to_dir_test_rule.bzl
Previously, when symlinking build dependencies to the .ext_build_deps folder, the build dependency tree would be traversed file-by-file, which was painfully slow in Windows. As part of my work to add meson support, the new examples of building 3rd party meson libraries would take ~30 minutes to merely symlink each file in the meson source tree.
This PR changes the symlink_to_dir and symlink_contents_to_dir shell commands to include a `replace_in_files` argument, which when True will revert to the previous behaviour. As I understand it, the previous behaviour is required so that certain files (`.cmake`, `.mk` etc) need file paths within them replacing, as they could contain file paths from a previous sandboxed or remote cached action. When the new `replace_in_files` argument is false, then …
=> Reduce build times (especially on windows) by symlinking directories

foreign_cc/built_tools/pkgconfig_build.bzl, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/make.bzl, foreign_cc/ninja.bzl, foreign_cc/private/framework.bzl, toolchains/native_tools/tool_access.bzl
Previously, some toolchain executables, e.g. make, pkg-config etc. were not added to the PATH correctly. As such, even if make and pkg-config were built from source, the system executables were used.
This commit modifies the tools_files attribute of the rules_foreign_cc framework to instead be "tools_data", which provides path to the executable and the target that provides it.
=> Add toolchain executables to the PATH

foreign_cc/private/runnable_binary_wrapper.sh, foreign_cc/utils.bzl
The runnable_binary_wrapper previously assumed that the working directory was in the runnable_binary runfiles directory, which is not the case when the runnable_binary is used as a tool in a dependant rule
=> Fix runnable_binary_wrapper when used as a tool in a dependant rule

foreign_cc/private/framework.bzl
This is required by dependents of the built pkgconfig toolchain
=> Add runfiles of dependency tools to the build

foreign_cc/private/cc_toolchain_util.bzl
fdo_instrument and fdo_optimize features should be disabled. These are not supported by external build systems.
=> Disable fdo features.

.bazelci/config.yaml, examples/third_party/iconv/iconv_repositories.bzl
These tests currently dont work on MacOS
=> Remove tests that depend on shared libraries

foreign_cc/private/cc_toolchain_util.bzl
When building in coverage mode, Bazel's cc_common.configure_features() adds coverage related flags, such as `--coverage` to the compiler and linker. However, if there is nothing in this library or its deps that are instrumented, we don't need to pass those flags, and avoid unncessary rebuilds.
=> Disable coverage when a C library is not instrumented

examples/.bazelrc, examples/WORKSPACE.bazel, examples/deps/apple_support.patch
Bazel 7.x is going to remove the CC toolchain that supports iOS and use the unix toolchain for macOS support. Since there are some tests that use the iOS toolchain we need to set that up for testing.
=> Add new darwin CC toolchain for tests

foreign_cc/private/framework/toolchains/macos_commands.bzl
=> Use python3 instead of python2 in macos commands

foreign_cc/private/framework.bzl
Hi, I found "installdir_copy" seems meaningless as output.  The "outputs.declared_outputs" has lib/ and include/. I think this's enough.
=> installdir_copy seems meaningless as output

.bazelci/config.yaml
Addressing downstream failures like: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2975#0187b105-46c4-43d6-8bae-771282e5d955
Context: https://github.com/bazelbuild/continuous-integration/pull/1492#issuecomment-1310082475
=> Skip minimal Bazel version support tasks in Bazel's downstream pipeline

.bazelci/config.yaml, .bcr/config.yml, .bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json, MODULE.bazel, WORKSPACE.bzlmod, examples/MODULE.bazel, examples/WORKSPACE.bazel, examples/WORKSPACE.bzlmod, examples/deps/repositories.bzl, foreign_cc/extensions.bzl
Adds configuration for publish-to-bcr app and adds the bzlmod files used in the existing BCR entry.
=> Add bzlmod support files.

foreign_cc/private/framework.bzl
If one wants to select a single output from a build (like a single shared library or a single static library), it's not possible to do so with the current code. The current code only creates an output_group for the declared binaries, which isn't sufficient.
This change creates an output group for all the artifacts including the includes.
Fixes #768
=> Allow selecting individual outputs from a rule

foreign_cc/make.bzl, foreign_cc/private/framework.bzl
I learned the hard way that the `make` build rule does not work out of the box with just any makefile, unlike other rules in this repository.
The single `make` example does *not* emphasize this, and it is important for the usability of the rule.
These are the things I learned:
- the `make( targets = [...])` invocation must at least execute an equivalent of `make install`, since all `out_*` params are relative to the *installation* directory, not to either the source or the buidkl directory.  So if your default target does not install anything, or you have a `install` make target, but don't invoke it, bazel will be unable to find your build outputs.
- The make file must either be able to recognize the `PREFIX=` env variable and use it, or have a different way of wiring the `$$INSTALLDIR$$` …
=> Adds some documentation specific to the `make` rule.

docs/BUILD.bazel
I'm not 100% sure the change will fix the issue...
=> Fix issue where meson documentation was blank on docs site

foreign_cc/cmake.bzl, foreign_cc/private/cmake_script.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/framework/platform.bzl, test/cmake_text_tests.bzl
Fixes cross-compiling from macos to linux.
see #997 for background.
I had to make a couple of extra changes to support this:
- Setting `CMAKE_SYSTEM_NAME` manually causes `CMAKE_SYSTEM_PROCESSOR` to not be set. This breaks some builds that expect this variable to be set like [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/4e52b66f342a803d3b8099b79607e3158d3a241c/CMakeLists.txt#L43).
- I made it so that the above variables are only set when cross-compilation is detected so that `rules_foreign_cc` only takes on responsibility of setting them when necessary.
=> fix linux cross compiling on macos

foreign_cc/utils.bzl
When using runnable_binary twice in the same package, windows_config_setting was being defined twice producing an error like:
Error in config_setting: config_setting rule 'windows_config_setting' in package '' conflicts with existing config_setting rule, defined at .../BUILD.bazel:29:16
This fix prefixes the setting with the name, the same as the other rules defined by the macro.
=> Fix multiple-definition error on windows_config_setting

README.md, foreign_cc/utils.bzl
Before this change, runnable_binary would only work on targets in external repositories. This is due to a limitation of the rootpath function, with more context in https://github.com/bazelbuild/bazel/issues/10923
This switches the macro to use rlocationpath, which handles this use-case. Using rlocationpath requires bazel 5.4.0, so this also updates the docs accordingly.
=> Allow runnable_binary to work on non-external targets

toolchains/built_toolchains.bzl
"calculated" with
```sh
curl -fsSL "https://github.com/mesonbuild/meson/releases/download/1.1.1/meson-1.1.1.tar.gz" | sha256sum -
```
See also https://bazelbuild.slack.com/archives/CA31HN1T3/p1698414059647089?thread_ts=1698412415.105119&cid=CA31HN1T3
=> Add missing sha256 for meson_src 1.1.1

foreign_cc/boost_build.bzl
This fixes #1071. I don't think there needs to be a tools_data, but the empty attribute is currently required.
=> Set an empty tools_data attribute for boost

foreign_cc/configure.bzl
I somehow missed this in #1095 for `configure_make`.
=> Advertise CcInfo provider

examples/third_party/mesa/BUILD.mesa.bazel, foreign_cc/meson.bzl, foreign_cc/private/cc_toolchain_util.bzl, foreign_cc/private/framework/helpers.bzl, test/convert_shell_script_test.bzl
- The PR sets CC and CXX in meson to the ones configured in bazel, instead of system's. 
- It also tries to merge and set CFLAGS, CXXFLAGS, LDFLAGS with implicit flags from bazel
- refactoring `split_arguments` helper function to be more readable and able to process arguments with quotes 
Fixes #1073
=> set CC and CXX and their flags in meson

examples/third_party/WORKSPACE.bazel
This is the proximate cause that resulted in https://github.com/bazelbuild/rules_foreign_cc/issues/1135
=> Fix `//openssl/...` by calling `openssl_setup()`

examples/third_party/BUILD.bazel
While investigating https://github.com/bazelbuild/rules_foreign_cc/issues/1135 I noticed some issues relating to the `test_suite()`s under `examples/third_party`
The set I targeted is based on the result of this query:
```
bazel query -k 'kind(test_suite,(//... - //:all))+tests(...)-tests(kind(test_suite,(//... - //:all)))' | sort
```
=> Sort tests under examples/third_party and add zlib to the list.

toolchains/built_toolchains.bzl
This PR adds mirrors to external repositories. The files were mirrored in https://github.com/bazelbuild/bazel/issues/20740
Hashes can be verified by creating a file with the mirror urls:
```text
https://mirror.bazel.build/pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
https://mirror.bazel.build/download.gnome.org/binaries/win64/dependencies/gettext-runtime_0.18.1.1-2_win64.zip
https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip
https://mirror.bazel.build/download.gnome.org/sources/glib/2.26/glib-2.26.1.tar.gz
https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib-dev_2.26.1-1_win64.zip
https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/0.63.0/meson-0.63.0.tar.gz …
```
=> Add mirrors to external repositories

foreign_cc/built_tools/cmake_build.bzl, toolchains/built_toolchains.bzl, toolchains/cmake-c++11.patch
On Windows using the msvc compiler, CMake can only be built using an existing binary CMake:
https://github.com/Kitware/CMake/blob/master/README.rst#windows
This means the existing `cmake_tool` fails to build for msvc (it tries to pass mingw compiler flags).  This change enables CMake to be built using a preinstalled CMake.
This change follows the pattern for pkg-config whereby unix/msvc have different build rules.
=> Build msvc cmake with prebuilt cmake

foreign_cc/private/make_env_vars.bzl, foreign_cc/private/make_script.bzl
There is a problem (or feature) with [nmake](https://learn.microsoft.com/en-us/cpp/build/reference/nmake-reference?view=msvc-170) where if you don't wrap the path for tools like CC in double quotes, nmake will only print out the command instead of executing it.
For example, given the following makefile:
```
CC = C:/my/toolchain/path/cl.exe
foo: main.cpp
$(CC) main.cpp
```
running nmake outputs:
```
F:\USERS\jsun\test>nmake
Microsoft (R) Program Maintenance Utility Version 14.16.27051.0
Copyright (C) Microsoft Corporation.  All rights reserved.
C:/my/toolchain/path/cl.exe main.cpp
```
I believe this problem hasn't surfaced till now as it is already quoting tool path on windows if they have a space in it. [ref](https://github.com/bazelbuild/rules_foreign_cc/blob/main/foreign_cc/private/make_ …
=> Fix tool path for nmake

foreign_cc/repositories.bzl, toolchains/built_toolchains.bzl
It was released a while ago, and, although I haven't been able to track down the exact reason why, I keep seeing jobserver failures (on linux) that don't happen on either 4.3 or 4.4.1, leading me to believe there's probably a bug in the new 4.4 jobserver code that was fixed in 4.4.1.
=> Add make 4.4.1

docs/BUILD.bazel, foreign_cc/private/runnable_binary_wrapper.sh
In the same vein as https://github.com/bazelbuild/rules_foreign_cc/pull/1093, we want to allow `runnable_binary` to run on targets without shared libraries
Copy and pasted from #1093 
> When using the runnable_binary macro with a binary e.g. diff that does not involve any shared libraries, the following error is produced:
>
> line 46: SHARED_LIBS_ARRAY[@]: unbound variable
>
> As find . -name "*${SHARED_LIB_SUFFIX}" -print0 does not return any results (thus SHARED_LIBS_ARRAY) , along with set -uo earlier in the script, this assumes that there will always be some shared library files.
Also, this PR introduces checks for whether the directory which is specified by `$RUNFILES_DIR` actually exists. If it does not exist, `cd`ing into it will crash the script (even though the rest of the script …
=> Increase resiliency of `runnable_binary`

.bazelci/config.yaml, .bazelci/windows-update-certs.ps1
This PR is an attempt to fix the CI windows failure caused by out of date TLS certificates, the solution is lifted from the python repo link here https://github.com/python/cpython/issues/80192#issuecomment-1093815328
I couldn't get the windows build to work locally, so CI was the testbed
=> Fix windows examples CI by upgrading TLS trust store

test/standard_cxx_flags_test/tests.bzl
This is required since some linking logic moved to starlark
Fixes https://github.com/bazelbuild/rules_foreign_cc/issues/1174
CC Greenteam @meteorcloudy
=> Add j2objc fragment to rules

foreign_cc/private/framework.bzl
` _normalize_path()` fails to normalize paths containing different drive letters eg.
`C:\foo;F:\bar` is converted to `/c/foo:F:\bar`
This change will ensure paths containing different drive letters are also normalized eg.
`C:\foo;F:\bar` is converted to `/C/foo:/F/bar`
=> Cater for different drive letters when normalizing path

toolchains/prebuilt_toolchains.bzl, toolchains/prebuilt_toolchains.py
At least since Ninja 1.10.2 the macos binaries are actually universal binaries which means that they support both `x86_64` as well as `aarch64`. I tested all versions manually to make sure we only mark ninja binaries as universal binaries when it's build for both architectures.
See:
```
➜ file ~/Downloads/ninja
/Users/dmeijboom/Downloads/ninja: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
~/Downloads/ninja (for architecture x86_64):     Mach-O 64-bit executable x86_64
~/Downloads/ninja (for architecture arm64):      Mach-O 64-bit executable arm64
```
This PR adds a new target `mac_aarch64` which contains the same artifact as `x86_64` where the CPU constraint is changed to `aarch64`.
Tested and seems to work …
=> Add aarch64 to prebuild library constraints for macos

foreign_cc/private/framework/toolchains/macos_commands.bzl
The copy_dir_contents_to_dir command currently ignores hidden files (e.g. dotfiles), leading to missing files after copying. Removing the * character in this case maintains the same behaviour, only with the inclusion of hidden files (.clang-tidy, .gitignore, etc).
=> Fix - Copy Dir ignores hidden files on macOS

foreign_cc/private/framework.bzl
RFCC relies on the PATH and INCLUDE msvc env vars to find the compiler/linker and includes files. 
When using an msvc toolchain with only relative paths, many of the foreign_cc rules break due to a reliance on absolute paths.
This MR prepends any relative paths in the msvc PATH and INCLUDES with `$EXT_BUILD_ROOT` to ensure all paths are still absolute without breaking hermeticity.
=> adjust relative msvc paths

toolchains/prebuilt_toolchains.bzl, toolchains/prebuilt_toolchains.py
Without this, on macOS runfiles fail to build because of `cmake-3.23.2-macos-universal/doc/cmake/html/_sources/generator/Borland Makefiles.rst.txt`
=> Exclude filenames with spaces from cmake toolchains

foreign_cc/private/framework.bzl, foreign_cc/private/framework/toolchains/windows_commands.bzl
'autoconf' applications often has a ./configure stage that checks the $srcdir (source directory). This is represented in foreign_cc by a combination of $EXT_BUILD_ROOT and a relative path to the source. This check fails on windows if $EXT_BUILD_ROOT contains '\\' since it is an escape char under unix. Therefore, we need to generate $EXT_BUILD_ROOT with '/' instead.
Generating $EXT_BUILD_ROOT with '/' present a different problem as now the resulting PATH variable becomes the format "/C:/path/to/a:/C:/path/to/b". Due to ':' being used as both window drive leter assignment and linux path delimiter, MSYS2 gets very confused and doesn't resolve this correctly. Therefore, we need this to become the format "/C/path/to/a:/C/path/to/b".
$EXT_BUILD_ROOT is sometimes passed through the 'env' …
=> fix: change cygpath to mixed mode

foreign_cc/private/framework/toolchains/windows_commands.bzl
This is an extension of https://github.com/bazelbuild/rules_foreign_cc/pull/1204.
PATH variable updated by the `##path##` primitive does not get expanded correctly on windows. 
For example:
```
##path## $$EXT_BUILD_ROOT$$
```
gets expanded to 
```
export PATH=C:/users/me/bazel_cache/xxxxxx/execroot/myrepo:$PATH
```
At the beginning, the `C:` gets incorrectly interpreted as 2 paths under msys.
1. `C`
2. `/users/me/bazel_cache/xxxxxx/execroot/myrepo`
The desired expansion here is:
```
export PATH=/C/users/me/bazel_cache/xxxxxx/execroot/myrepo:$PATH
```
Which correctly gets interpreted as 1 path.
=> fix: path expansion on windows

foreign_cc/private/framework.bzl
During our migration to Bazel 7, some of our cmake() rules broke. It turns out there is a new field in CcCompilationContext to account for external includes, as opposed to internal system_includes.
See https://github.com/bazelbuild/bazel/commit/a6ef0b341a8ffe8ab27e5ace79d8eaae158c422b
=> Update framework.bzl to account for externalIncludes

foreign_cc/cmake.bzl
Reverts bazelbuild/rules_foreign_cc#1087
=> Revert "cmake: use variable expansion on generator args"

foreign_cc/private/runnable_binary_wrapper.sh
I've ran into a bug where a top-level target is able to use runfiles, but if a target is in the dependencies of the top-level target, it is not able to detect them. To fix this, I patched `rules_foreign_cc` to re-export the env cars used to find runfiles, and that seems to work
=> Re-export runfiles env vars so that dependencies can use them

foreign_cc/cmake.bzl
When building proj I need to pass the sqlite3 binary via a cache entry, like `{"EXE_SQLITE3": "$(execpath @sqlite3//:shell)"}` but that requires that cache entries are also expanded.
=> Apply expand_locations_and_make_variables to cache_entries

foreign_cc/cmake.bzl
Reverts bazelbuild/rules_foreign_cc#1240
=> Revert "Apply expand_locations_and_make_variables to cache_entries"

foreign_cc/private/framework/toolchains/freebsd_commands.bzl, foreign_cc/private/framework/toolchains/macos_commands.bzl
On BSD-based distro/MacOS, using `cp -L -R {source}/` ignores files or directories with a leading dot. If users have GNU-based coreutils installed on their BSD/Mac system (via Nix for e.g.), `cp -L -R {source}/` would also copy the source directory _underneath_ the target directory, which is not what we want.
This PR changes both the `copy_dir_contents_to_dir` implementation for BSD and MacOS such that it works regardless of whether user has GNU or BSD coreutils installed.
=> Portable copy_dir_contents_to_dir

foreign_cc/meson.bzl
The logic for generating the Meson script conditionally exports some variables such as `LDFLAGS`, `CFLAGS`, and `CXXFLAGS`, ignoring what the user may have specified using the `env` attribute of the `meson` rule.
Prepend the user specified flags at the end when exporting these variables.
=> Do not clobber user environment variables in Meson script

foreign_cc/built_tools/make_build.bzl, foreign_cc/built_tools/pkgconfig_build.bzl, foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/private/BUILD.bazel, foreign_cc/private/cmake_script.bzl, foreign_cc/private/detect_xcompile.bzl, foreign_cc/private/framework.bzl, foreign_cc/private/framework/platform.bzl, test/cmake_text_tests.bzl
This teaches the autotools-based configure script to pass --host when
cross-compilation is detected. This fixes at least part of #1082. This
functionality is off by default (because configure_make can be used for
non-autotools builds) and can be enabled by passing configure_xcompile
to configure_make.
This functionality is also extended to the built_tools that use autoconf
(pkg-config and make).
It also does a bit of generalization to make it easier to support more
platforms in the future, and adds s390x to the detected arches.
=> configure_make: support autotools cross-compilation

MODULE.bazel, WORKSPACE.bazel, docs/WORKSPACE.bazel, examples/third_party/zlib/BUILD.bazel, examples/third_party/zlib/BUILD.zlib.bazel, examples/third_party/zlib/CMakeLists.txt, examples/third_party/zlib/test_shared_zlib.sh, foreign_cc/private/BUILD.bazel, foreign_cc/private/framework.bzl, foreign_cc/repositories.bzl
This MR adds a new `dynamic_deps` attr that allows the libs created by cc_shared_library targets to be added as deps.
Closes https://github.com/bazelbuild/rules_foreign_cc/issues/1242
=> add support for cc_shared_library deps

examples/third_party/BUILD.bazel, examples/third_party/glib/glib_repositories.bzl, foreign_cc/repositories.bzl, toolchains/built_toolchains.bzl
This is an attempt to fix the macOS CI issues mentioned in https://github.com/bazelbuild/rules_foreign_cc/issues/1244.
Also noting https://github.com/bazelbuild/rules_foreign_cc/pull/1251 disabled the broken tests. Whereas this MR should fix the tests.
The original problem should be a meson issue and not a foreign_cc one. see https://github.com/mesonbuild/meson/pull/12574. Although, I couldn't track down what introduced the problem.
I got the idea that it is a meson problem, given `-Wl,--version` is not generated as a part of our `cxx_linker_executable` or `cxx_linker_shared`.
The quick solution is to update our default meson version to a version that includes the fix.
Had to also update glib, as after the meson fix it was running to this an issue similar to …
=> fix meson tests for macOS CI

foreign_cc/private/make_env_vars.bzl
Another PR regarding flags being set in `env`. Currently there is no solution to set `CPPFLAGS` via `configure_make`. If you set them in the environment, they will be clobbered by the build system flags. If you set them via `configure_options` or `configure_prefix` (I saw someone doing that somewhere), then they clobber the build system `CPPFLAGS` meaning you cannot use dependencies (since this is how header files from dependencies are made during the build).
=> Merge user provided CPPFLAGS with build system CPPFLAGS

MODULE.bazel, WORKSPACE.bzlmod, examples/MODULE.bazel, toolchains/built_toolchains.bzl
`glib_dev` was incorrectly loading a symbol from `rules_cc` which causes visibility issues on windows bzlmod.
=> Remove dependencies on rules_cc

examples/third_party/apr/apr_repositories.bzl
Inspired by https://github.com/foundationrobotics/rules_foreign_cc/commit/0bf2b360ef22d05189fdae1672a6a2223854706f 
But instead of using vulnerable version 1.7.4 with CVE-2023-49582 we use 1.7.5
Check https://downloads.apache.org/apr/CHANGES-APR-1.7
=> Bump APR version to 1.7.5. Make CI/CD green again.

examples/third_party/apr/apr_repositories.bzl, foreign_cc/built_tools/pkgconfig_build.bzl
=> Fix for #1239

foreign_cc/utils.bzl
In #1267 there was an issue where, somehow, the wrapper script ended up as a zero-length file but the action succeeded (resulting in storing a zero-length file instead of the script in the caches). genrules are documented as running inside `-ueo pipefail` so it seems like this should be impossible...
In any case, this avoids using >$@ because the > runs before the command itself does, creating a zero-length file before populating it, and is the only way I could think of that this ends up as an empty file. Hopefully, if the problem repeats, genrule will notice that the file didn't get created and fail.
SH_BINARY_FILENAME also wasn't used, so this skips a step.
=> runnable_binary: avoid using > on the output file

.bazelci/config.yaml
Fixes https://github.com/bazelbuild/rules_foreign_cc/issues/1274
=> Bazel CI config: explicitly enable workspace wherever Bzlmod is disabled

examples/third_party/curl/BUILD.curl.bazel, examples/third_party/libgit2/BUILD.libgit2.bazel, examples/third_party/libssh2/BUILD.libssh2.bazel, foreign_cc/cmake.bzl, foreign_cc/private/cmake_script.bzl
see https://github.com/bazel-contrib/rules_foreign_cc/issues/887
Rather than creating a new provider, this MR utilizes `ForeignCcArtifactInfo:gen_dir` to add a `$$EXT_BUILD_DEPS/<package>`  to `CMAKE_PREFIX_PATH` for each external `ForeignCcDepsInfo`.
It eliminates the need for custom `CMAKE_PREFIX_PATH` or `<package>_ROOT` cache entries on `cmake` rules.
=> add foreign_cc deps to cmake prefix path

foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/private/framework.bzl
BUILD_TMPDIR and EXT_BUILD_DEPS were used in the wrapper script, but they weren't actually defined. This wasn't caught because the script prelude (which sets bash -u) wasn't used either.
This fix:
- Adds the missing script prelude to the wrapper script
- Generalizes get_env_prelude slightly so built_tools can use it directly, without needing to override variables
- Passes the env prelude to wrapped_outputs so it can set those same variables
- Prints out the paths to the build and deps dir at the end of a failed script, to make it easier to debug failed builds.
=> fix undefined variables in the wrap_outputs script

foreign_cc/built_tools/pkgconfig_build.bzl
The target field on the make tool data should be None when using a preinstalled toolchain according to the docs, this fixes the pkgconfig tooling to handle that case.
=> fix: builds using preinstalled_make no longer break during pkgconfig

foreign_cc/private/cc_toolchain_util.bzl
Bazel's `File().path` method will return forward-slashed paths; this means if you pass a flag like `"/FI" + f.path` it'll end up looking like `/FIpath/to/thing`; however, `_convert_flags` was converting all `/` to `-`, which ended up breaking the path. This makes sure to only replace the _first_ `/`.
=> correct overeager slash conversion on windows

.gitattributes
Use `.gitattributes` to force the files that are not recognized by Github Linguist as Starlark to be highlighted as such.
=> feat: force GH Linguist syntax highlight

MODULE.bazel, README.md, docs/README.md, docs/book.toml, docs/index.md, docs/root/book.toml, examples/README.md, examples/third_party/openssl/BUILD.openssl.bazel, foreign_cc/cmake.bzl, foreign_cc/private/cmake_script.bzl
Update links after the repo transfer (#1290).
Fixes #1297
=> fix: move all bazelbuild links to bazel-contrib

.bazelci/config.yaml, .bcr/metadata.template.json, .github/docs-0.1.0.patch, .github/docs-0.2.0.patch, .github/docs-0.3.0.patch, .github/workflows/pages.yaml, .github/workflows/release_prep.sh
I missed some links in #1315 😕
I was using `rg` to grep and I forgot that it will respect `.gitignore` and exclude those files.
I hope I got them all this time!
=> fix: move more bazelbuild links to bazel-contrib

.github/docs-0.1.0.patch, .github/docs-0.10.1.patch, .github/docs-0.2.0.patch, .github/docs-0.3.0.patch, .github/docs-0.5.0.patch, .github/docs-0.5.1.patch, .github/docs-0.6.0.patch, .github/docs-0.7.0.patch, .github/docs-0.7.1.patch, .github/docs-0.8.0.patch, .github/docs-0.9.0.patch, .github/workflows/pages.yaml, docs/root/src/index.md, version.bzl
The [pages workflow is failing](https://github.com/bazel-contrib/rules_foreign_cc/actions/runs/11706830028/job/32604817856) due to deprecated versions of actions/upload-artifact.
I believe this is why the docs are not updating (e.g. the Meson docs are still blank after #1060 landed).
For more info, see:
* https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
* https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
* https://github.com/actions/upload-artifact
This is also needed for docs generation, see `docs/tools/workspace_status.sh`
=> fix: docs pages

foreign_cc/private/transitions.bzl
The toolchain attr is not currently selectable making builds that need to handle multiple platforms (incl windows) very verbose. The target needs to be declared at least twice, once for windows and once for unix based platforms.
By making it selectable, even though we still need a rule() and rule_variant() declaration, we can wrap it in a macro and only expose the macro to the user.
=> fix: let 'toolchain' attr be selectable

foreign_cc/configure.bzl, foreign_cc/make.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/make_env_vars.bzl, foreign_cc/private/make_script.bzl
`configure_make()` and `make()` both resolves `LDFLAGS` to `CxxToolsInfo.cxx_linker_executable`. This hard codes the linker executable flags and does not provide a way to use the `cxx_linker_shared` flags. While this works for most use cases,  it does not work for all. An example is when we enable `--force-pic` which appends `-pie` to our executable linker flags. `-pie` is only applicable when linking executables and will fail on shared libraries since it cannot find a `main()` function. 
This MR solves this problem by introducing 2 new attributes to `configure_make()` and `make()`. 
* `executable_ldflags_vars`
* `shared_ldflags_vars`
Each is a string_list of variable names that the target project uses for executable ldflags and shared ldflags. For example, in openssl3 …
=> feat: configurable ldflags

foreign_cc/configure.bzl, foreign_cc/make.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/make_env_vars.bzl, foreign_cc/private/make_script.bzl
Linker make vars generated for dependent packages used -L which is not supported on msvc. -LIBPATH is needed.
=> msvc: fix make var for windows deps

.bazelci/config.yaml, MODULE.bazel, WORKSPACE.bazel, docs/BUILD.bazel, examples/MODULE.bazel, examples/cmake_crosstool/static/BUILD.bazel, examples/cmake_hello_world_lib/static/BUILD.bazel, examples/third_party/gn/BUILD.bazel, examples/third_party/libpng/BUILD.bazel, examples/third_party/openssl/BUILD.bazel, examples/third_party/zlib/BUILD.bazel, foreign_cc/BUILD.bazel, foreign_cc/repositories.bzl, foreign_cc/utils.bzl
This is needed for bazel 8.
Fixes #1336
=> Add dependency on rules_shell

foreign_cc/private/framework.bzl
Calling foreign build systems can be fraught, since a lot of custom-written rules do things like execute gcc from the path, instead of using the CC variable. This makes PATH ordering important, to make sure that even if that happens, the toolchain tools get used anyway (and not, e.g. from /usr/bin)
One way to handle that at the toolchain level is to use env_entries (e.g.
https://github.com/bazelbuild/rules_cc/blob/8c94e11c2b05b5f25ced5f23cd07d0cdd36edc1a/cc/private/toolchain/windows_cc_toolchain_config.bzl#L1246) to add the toolchain to the path. You can control whether the toolchain gets prepended or appended by using the token $PATH, e.g. /my/path:$PATH vs $PATH:/my/path.
Unfortunately, the _correct_path_variable helper was unconditionally prepending $PATH to the toolchain path, even …
=> framework: avoid forced path suffixing

examples/third_party/glib/BUILD.glib.bazel, foreign_cc/meson.bzl, foreign_cc/private/cc_toolchain_util.bzl
This aligns this to what other tools are doing. The `_join_flags_list()` pattern is also used for other foreign build tools.
This is required to fix `--sysroot` flag even without cross compiling for example when using in combination with a hermetic toolchain (for example `toolchains_llvm`). This flag is only available in `get_flags_info()` and for the complicated ffmpeg build this works flawlessly. Without it being absolute, it doesn't work.
This is required to fix `libdav1d` in #1295.
=> Improve flags handling for meson

foreign_cc/cmake.bzl, foreign_cc/private/cmake_script.bzl, test/cmake_text_tests.bzl
For some projects, it's sufficient to just have these in the cache, but for abseil, it appears to break unless they're in the toolchain file. The error is similar to the one in [this bug](https://github.com/abseil/abseil-cpp/issues/1241) where it tries to use x64 flags for an aarch64 target.
The [cmake docs](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#toolchain-files) also indicate they're supposed to be in the toolchain file, so this aligns there, too.
=> cmake: put CMAKE_SYSTEM_{NAME,PROCESSOR} into toolchain file

foreign_cc/built_tools/make_build.bzl, foreign_cc/built_tools/pkgconfig_build.bzl, foreign_cc/built_tools/private/built_tools_framework.bzl
sysroot can be specified with as `--sysroot=<meow>` or `--sysroot <meow>`. This fix allows for the latter use case as well.
=> fix sysroot for make and pkgconfig built tools

foreign_cc/extensions.bzl, foreign_cc/repositories.bzl
repos registered via workspace mechanisms take priority over repos registered via bzlmod. This means that when the `tools` extension calls `rules_foreign_cc_dependencies`, all of the repos registered become private copies (called something like `@@_main~tools~bazel_skylib` reflecting that the `tools` extension registered a repo called `bazel_skylib`). This is often fine, but for anything that declares constraints (like the platforms repo) this causes rfcc to use (e.g.) `@@_main~tools~platforms//os:linux` instead of `@platforms//os:linux`, which causes a lot of things to break!
https://github.com/bazel-contrib/rules_foreign_cc/pull/1373#issuecomment-2696043851
=> bzlmod: prevent extension from registering repos

examples/MODULE.bazel, foreign_cc/private/cmake_script.bzl, foreign_cc/private/framework/platform.bzl, foreign_cc/repositories.bzl
ppc64le support was added to [bazel_platforms](https://github.com/bazelbuild/platforms/blob/dd28c190c563531c06ba3bd64eca1cc9ca3e667f/cpu/BUILD#L148) in 0.0.8, and rfcc has an [explicit dep on 0.0.11 now](https://github.com/bazel-contrib/rules_foreign_cc/blob/dfc81310cb56793242b521f10492bbb8ebf1f312/MODULE.bazel#L11) so it's probably safe to add it
=> add xcompile support for ppc64le for autotools and cmake

examples/cmake_synthetic/BUILD.bazel, examples/third_party/gn/BUILD.gn.bazel, foreign_cc/built_tools/pkgconfig_build.bzl, foreign_cc/configure.bzl, foreign_cc/private/configure_script.bzl, foreign_cc/private/framework.bzl
postfix_script did not support make vars which means we cannot use things like $(execpath :target) in it. This limited the functionality of the attribute.
Note, this is a breaking change as $$ wrapped variable declaration and single $ shell variable declaration will no longer work in postfix_script e.g. $$INSTALLDIR$$ and $INSTALLDIR. Need to used shell variable with an escaped $ like $$INSTALLDIR.
=> feat: support make vars in postfix_script

foreign_cc/private/BUILD.bazel, foreign_cc/private/cmake_script.bzl, test/cmake_text_tests.bzl
Target built with `cmake` are currently unable to find the dependencies `.pc` files.
This PR attempts to fix it
=> Allow cmake to use pkg-config for dependencies

foreign_cc/private/cc_toolchain_util.bzl, foreign_cc/private/framework.bzl
Some third party cmake packages append a suffix to static libs eg. cares:
```
out_shared_libs = [
"libcares.so",
],
out_static_libs = [
"libcares_static.a",
]
```
`cmake` will treat these as separate libs, creating separate `CcInfo` `<LibraryToLink>`'s for each:
```
<LinkerInput(libraries=[<LibraryToLink(static_library=libcares_static.a)>, <LibraryToLink(dynamic_library=libcares.so)>]>
```
This creates a different `linking_context` compared to packages that have matching filenames, and can lead to changes in linking behavior when used as a dep.
This change introduces a new attribute `static_suffix` that provides a hint to allow association of the suffix-appended static lib with the shared lib:
```
static_suffix = "_static",
```
results in
``` …
```
=> add a static_suffix attr

foreign_cc/private/cc_toolchain_util.bzl
Use the builtin `removesuffix()` in toolchain utils.
Fixes https://github.com/bazel-contrib/rules_foreign_cc/commit/cd59e932ec2a1c501ccaf1e4dd056aa3c68117f7
=> use string.removesuffix

foreign_cc/private/cc_toolchain_util.bzl
We currently only absolutize relative paths starting with either `external/` or `<top-package-name>/`. This commit changes that to include paths that begin with `bazel-out/` to allow rules_foreign_cc to work with Bazel-generated sysroots.
=> Absolutize paths beginning with `bazel-out/`

foreign_cc/private/cmake_script.bzl, foreign_cc/private/framework/platform.bzl
This PR adds the definitions for the CPUs and OSes used in WebAssembly, specifically, for Emscripten. Just testing in CI for now.
=> Add support for Emscripten

examples/meson_simple/BUILD.bazel, examples/meson_simple/code/BUILD.bazel, examples/meson_simple/code/clang_wrapper.sh, examples/meson_simple/code/liba.cpp, examples/meson_simple/code/liba.h, examples/meson_simple/code/meson.build, examples/meson_simple/test_introspect.sh, examples/meson_simple/test_libb.cpp, foreign_cc/meson.bzl, foreign_cc/private/framework.bzl
* Add support for `targets` to meson rule: Meson didn't support the `targets` attribute in `CC_EXTERNAL_RULE_ATTRIBUTES` that other rules use. This is useful for running other Meson commands such as `meson test` or `meson introspection`.
* Add a new `out_data_files` output to be able to capture certain files from commands that don't yield the usual "compilation output".
* Modify the outputs so that `out_data_files` can override all other outputs without failing (e.g. while forcing `out_lib_dir` and `out_include_dir` to `""`).
* Add two simple tests to exercise the `meson` rule and the new support for Meson targets such as `introspect`.
=> feat: meson additional targets

foreign_cc/built_tools/private/built_tools_framework.bzl, foreign_cc/cmake.bzl, foreign_cc/configure.bzl, foreign_cc/private/framework.bzl, toolchains/native_tools/tool_access.bzl
This fixes a bug where cmake and configure_make rules does not get env data from toolchains built by native_tool_toolchain rule.
=> fix: allow rules to consume tools env data

foreign_cc/private/framework.bzl
Using "\"$EXT_BUILD_ROOT\"/" with the extra \"s is unnecessary. The extra quote should be applied to string where this is used. Otherwise this causes odd path problems for msvc.
Notably, in get_env_prelude, this causes LIB and INCLUDE env vars to expand to something like:
LIB="\\\\\"$EXT_BUILD_ROOT\\\\\"/external/toolchain..." This is not recognized as a valid path when running through msys2 on windows and causes all kinds of pain.
=> fix: broken msvc builds

foreign_cc/private/framework/toolchains/macos_commands.bzl
The replace_symlink implementation on darwin called out to the darwin system trampoline python3 version; this breaks with toolchains that have a hermetic SDKROOT (because the trampolines don't know how to read a relative value, and bazel registers it as an absolute path violation if it's absolute).
realpath appears to have been added to the osx base system in Ventura (13), and according to https://endoflife.date/macos Monterey (12) went end of life back in September 2024.
=> fix: remove system dependency on python3
